### ISSUE TITLE
Mark use_tibble() as questioning

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#1046]
Because it doesn't do that much, and it suggests hundreds of other similar functions that might be added to usethis.

**Comment by charliejhadley** [comment]
I made the initial PR for `use_tibble()` as I was working on data packages where I wanted the package to guarantee a tibble was returned instead of a plain data.frame, and I think it's just as important as its sibling `use_data_table()`.

Unfortunately, but unsurprisingly folks have not often mentioned `use_tibble()` directly in their commit messages so its difficult for me to make a case for it being used widely. However, here are a few places where I can show it had value to users:

https://sharla.party/post/usethis-for-reporting/
https://rstudio4edu.github.io/rstudio4edu-book/data-pkg.html
https://www.hvitfeldt.me/blog/usethis-workflow-for-package-development/

The current workings of `use_tibble()` are far from my initial PR and if it is polluting the namespace that's horrible, but I feel there is a need for this functionality in `{usethis}`

**Comment by hadley** [comment]
I'm not saying it's not useful, more that I don't think it's a good fit for usethis. It also goes against our usual recommendation to use `tibble::as_tibble()`.  `use_data_table()` was added primarily to match `use_tibble()` so I don't think its existence is a good argument for `use_tibble()`.

`use_pipe()` is a different beast because it's primarily about _re-exporting_ the pipe, not about simply using it.

**Comment by charliejhadley** [comment]
Ah, I did employ reverse causality for the data.table function. Thanks as always for explaining your thought process, much appreciated 🙂

**Comment by malcolmbarrett** [comment]
Do you see a more generalized form as an option? Something like `use_import(pkg, function = NULL)` (not a great name but you get the drift). I completely see the argument that it's not doing much (roxygen is doing the heavy lifting here and is not that complicated). **But** I feel like usethis does bring something to the table here: a standardized opinion on where to put these types of imports. Putting them in the package doc (if it exists) is very nice to me, and I often wish it was easier to find import statements like these when looking at package code (the namespace file usually being so crowded). I like that this automation results in a sensible place to check. 

That all said, it wouldn't be a huge loss. I like both `use_tibble()` and `use_data_table()` but your arguments make sense (in fact, I think I may have prompted this issue after proposing a new `use_*()` function in this style!). Just using roxygen instead is not too rough

**Comment by jennybc** [comment]
cc / fyi @Michael Chirico

I'm marking both `use_tibble()` and `use_data_table()` as "questioning".

**Comment by jennybc** [comment]
cc / fyi @MichaelChirico (using correct tag this time)

**Comment by MichaelChirico** [comment]
noted, thanks! & makes sense
