### ISSUE TITLE
Helper to bump GH actions cache

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/usethis#1101]
GitHub actions sometimes needs a little help to reset its cache when packages / versions are out of sync.

See https://github.com/r-lib/pkgdown/issues/1301 fixed by the approach in https://github.com/r-lib/pkgdown/commit/31e72be6866faa4f09132c6d2e3d6fc56e9dda3d

This approach feels quite brittle and will not be obvious to new users. Something like `usethis::use_github_action_bump_cache()` might be useful.

**Comment by jennybc** [comment]
I was thinking about this too, but also fear how robust this helper can be made. For example, I have to tweak the basic workflow a fair amount for some packages (not for the bit of yaml we're talking about, though, tbh). The real answer is for Github Actions to provide a sane way to invalidate the cache.

@jimhester Any thoughts?

**Comment by jennybc** [comment]
@jimhester Has the landscape changed here? In particular, is this closer to being fixed upstream?

**Comment by jimhester** [comment]
No, nothing has changed

**Comment by jennybc** [comment]
Do you think a usethis helper is a good or bad idea @jimhester?

**Comment by jennybc** [comment]
I've thought about this more.

I think, if any smarts get written, that should live in r-lib/actions.

Why? Because the definitive workflow files live there. So any code that makes a surgical edit to the workflow files has to be co-maintained, so they evolve together and we have internal consistency.

I wonder if there's an approach to handling the name of the cache that puts it within reach of a meta-Action. So using one of these approaches:

  * The `pr-commands` approach: <https://github.com/r-lib/actions/blob/master/examples/pr-commands.yaml>, where special comments in an issue or PR thread causes a PR to get made or updated.
  * The `skip ci` approach I took for tests and pkgdown in googlesheets4: <https://github.com/tidyverse/googlesheets4/blob/ab581e32cf8eb274b731c0de41bc60a84069f37e/.github/workflows/pkgdown.yaml#L15>, where special keywords in a commit message cause something to happen.

We are firmly in territory where I think @jimhester has the most informed opinion.

**Comment by jennybc** [comment]
Basically, can we put this integer that we increment somewhere that it's easier to increment programmatically?

**Comment by jimhester** [comment]
I don't think there is anything we could do that would give a substantial improvement.

Right now you need to bump two numbers in the workflow yaml file, the best we could do is make it so you only had to bump one number, but at the cost of complicating the workflow steps with extra indirection.

**Comment by hadley** [comment]
I don't think there's anything that usethis can do about this. We are just waiting for Github to expose some UI for clearing the cache since it's such a common need. Until then, you'll just need to increment the counter in the actions yaml, like an animal.
