### ISSUE TITLE
use_version does not commit version changes in CI

### ISSUE THREAD

**Issue by sidohaakma** [r-lib/usethis#1135]
We used to use use_version in our Jenkins CI, it committed version changes in the DESCRIPTION file. At this moment it does not do that anymore when running non-interactively

Use `use_version` in a non-interactive environment (CI). For example:
```r
usethis::use_version('dev')
✔ Setting active project to '/home/jenkins/agent/workspace/nis_molgenis-r-datashield_master'
✔ Setting Version field in DESCRIPTION to '1.1.0.9000'
# it stops here, please don't stop here ;-D.
```

[Jenkins_log_error.txt](https://github.com/r-lib/usethis/files/4616690/Jenkins_log_error.txt)

**Comment by jennybc** [comment]
What's different about olgenis_molgenis-r-mosaic_master (commits) and nis_molgenis-r-datashield_master (does not commit)?

I don't really know what I'm looking at and need you to translate your Jenkins log for me. Because from where I sit it looks like the same usethis command leads to different results in 2 different contexts. How sure are you that both projects are also Git repos and that a Git user has been configured on both?

`use_version()` is being tested here on CI, FWIW:

https://github.com/r-lib/usethis/blob/master/tests/testthat/test-use-version.R

This will get the most traction is you can reproduce the problem outside of Jenkins. I don't really think there's some special interaction between usethis and Jenkins.

**Comment by sidohaakma** [comment]
@jennybc The builds differ in R version. The mosaic build is done in 3.5.2 context, which represents a version of `usethis::use_version` specifically: 1.4.0. The DataSHIELD build is done in 3.6.3 which represents `usethis::use_version` 1.5.1: . In the new version of use_version, the UI is always needed to commit the DESCRIPTION. You can not commit non-interactively anymore. When I look at the code does `return invisible()` before it does `git_commit`.

**Comment by jennybc** [comment]
https://github.com/r-lib/usethis/blob/368714a4f487dce4719ac8a002383d719f73cd64/R/git.R#L33-L35

Yeah, so we have no way to commit without user interaction. My immediate reaction is that I am OK with that and not eager to start threading some new argument (e.g. `commit = TRUE`) through high-level functions like `use_version()`. Its primary purpose is to change the version, which it does here. If you want to also commit such a change in a non interactive session, your script will need to do that explicitly in a subsequent step. Depending on the context, you could even use unexported usethis functions to do this, e.g. `usethis:::git_commit()`. Or use git2r or gert or system git.
