### ISSUE TITLE
Show warning only once

### ISSUE THREAD

**Issue by jaheskje** [r-lib/usethis#1155]
Using usethis::use_warn in functions will show warning every time the function is called. It would be beneficiary to have an argument for only showing the warning once/first time.

**Comment by jennybc** [comment]
If you want to be clever / humane about frequency of warning, then you have to keep track of different warnings and enforce this for each "warning ID". That is well beyond the scope of what `ui_warn()` does.

The lifecycle package has logic for this, since it's used to calibrate how often to warn about deprecated functions or arguments. If you need this feature, you might want to poke around the source there for ideas.

https://lifecycle.r-lib.org
