### ISSUE TITLE
use_github_action("pkgdown") fails without error message

### ISSUE THREAD

**Issue by ElsLommelen** [r-lib/usethis#1161]
I aimed to add a github.io-website to my package by using the following code and pushed the changes to a feature branch on github (generated `.yaml`-file and changes in `.Rbuildignore`, [this commit](https://github.com/inbo/forrescalc/commit/6ae28b26faa81f91f57468c6984980748c6ecc9d))
```r
usethis::use_pkgdown()
usethis::use_github_action("pkgdown")
```
When merging the changes to the master branch, the run failed without showing an error: [the report](https://github.com/inbo/forrescalc/runs/798313752) only mentions successful installations.

I tried adding a branch `gh-pages` with only one empty file index.html (as it seemed not possible to push an empty branch) because I was not sure if it should be added manually, but the run [failed again](https://github.com/inbo/forrescalc/runs/799430785) with exactly the same report.

Nevertheless, a while ago the same procedure worked fine when applying it to another package.  I was then pleasantly surprised that the setup went so easy and fast.

**Comment by jennybc** [comment]
Thought @jimhester ?

I think this might actually be a failure to install R, but, yes, if I am right, it's basically impossible to tell this from the log.

**Comment by jennybc** [comment]
We are having general problems with the macOS installation in workflows lately, because there's a gap between when a patch release happens and when an installer is available. @jimhester made a recent commit https://github.com/r-lib/actions/commit/580614d03539b2ee4ad3a44e491e51622c666ee2 that aims to help.

So this might be something that just works itself out.

In any case, I'm fairly confident the problem does not lie in usethis. I think it's in the larger ecosystem. If it persists, https://github.com/r-lib/actions/issues is probably the best place to discuss.
