### ISSUE TITLE
Which functions need host and auth_token?

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#1162]
Look at the presence / absence of `host` and `auth_token` arguments and figure out if there's any rhyme or reason to it.

**Comment by jennybc** [comment]
@ijlyttle Do you have any commentary you want to add here? Should these even be arguments at all, ever? Re: the token, once can work around that because it's "just" an env var. And I could make the GitHub API `host` an env var too.

I can't imagine normal users ever set these in a direct call. In which case, this is mostly about wrapping. And in that case, it's not so bad to use `withr::local_envvar()`.

**Comment by ijlyttle** [comment]
I like the idea of turning these into purely environment variables, deprecating the arguments. 

I had put together some "napkin-sketches" in #846, but I prefer your idea as it seems the "simplest thing that will work". 

I put together a (surely incomplete) list of functions that might be touched. Thinking through that:

- could `remotes::install_github()` follow the same convention? Would it need to?
- the sense of `host` is different for `browse_github_token()` (the web host v. the API host) than for the other functions. This might need some trickery.

On my end, I could write a function, `with_acme()`, that could wrap everything - which would be very clean 😀

I'll add more things as I think of them, also to ping @cderv!

**Comment by jennybc** [comment]
I ended up discussing this in my 1-on-1 with @Hadley today. He suggested stashing some information about this (the GitHub host) in the repo-level git config. usethis already leaves some notes for itself in git config re: PR work, so we've already started this practice.

We also realized there's not much point in implementing this until / unless you also provide some way to use one PAT for GitHub.com and another PAT for GHE. I know all of this is stuff you've raised before.

**Comment by ijlyttle** [comment]
I can see how stashing the information would make things easier.

Maybe options could be useful here?

I think you would need them for `use_github()` and `create_from_github()` (maybe others?)

The defaults could be something like:

```r
# using rlib.github.* in case remotes::install_github() might like to use
options(
  rlib.github.url_api =  "https://api.github.com",
  rlib.github.env_token = "GITHUB_PAT"
)
```

For GHE, something like this could be put in an internal package:

```r
#' @examples
#' with_acme_ghe(create_github())
#'
with_acme_ghe <- function(code) {

  new_opts <- 
    list(
      rlib.github.url_api =  "https://acme.github.com/api/v3",
      rlib.github.env_token = "GITHUB_PAT_ACME"     
    )

  withr::with_options(new_opts, code)
}
```

If I understand the mental model, the Acme info would be stashed for use later.

Could this be a possiblity?

**Comment by hadley** [comment]
I don't think you want global options because that would affect all calls, when really you want it scoped to a repository. Instead, I think `use_github()` and `create_from_github()` will continue to have a host argument; and if it's specified would use `GITHUB_ENTERPRISE_PAT` rather than `GITHUB_PAT` (we are deliberately not going to help with the case of multiple GitHub enterprise accounts because that is more effort than we want to expend). When you create a repo this way, usethis would automatically mark the remote as "Github: true" (or similar) so that other functions know that you can manipulate the git remote to create the GitHub API endpoint by taking the hostname and adding `/api`.

(We'd also provide some fallback so that the first time you use a function that uses the GitHub api on an existing repo, it would attempt to discover if any of the existing remotes are GitHub compatible, then record its findings in the git config).

**Comment by ijlyttle** [comment]
If I understand correctly:

- the `host` argument would appear only in "create" functions, like `use_github()`, `create_from_github()`, and possibly `remotes::install_github()` (out of scope here, I know, but in the interests of consistency).

- if the `host` is `NULL`, or `https://api.github.com`, then `GITHUB_PAT` is used; otherwise `GITHUB_ENTERPRISE_PAT` is used.

- upon success (for usethis functions), the host and token envvar-name are stashed for future use by `use_github_links()`, `pr_init()`, etc.

For someone at Acme, they could provide a package with functions, `use_github_acme()`, `create_from_github_acme()`, `install_github_acme()`, that would provide a different default for `host`, then pass the rest through. 

I think that would work from my end, and I am at your-all's service to help make it work

**Comment by hadley** [comment]
Your first two points are correct, but the last point is slightly off: the host is already implicitly stored in git config in the remote url, we'd now just mark that this remote works with the GitHub api.

**Comment by ijlyttle** [comment]
Lights are coming on for me now... 

The magic will be a set of functions that use the remote url to get what you need, assuming that it's a GitHub remote - which you will know because you will have stashed *that* information. 

Thanks!
