### ISSUE TITLE
Adding project .Renviron to .gitignore when initiated with `edit_r_environ`

### ISSUE THREAD

**Issue by Athanasiamo** [r-lib/usethis#1256]
When creating a project specific .Renviron, it would be convenient that it was added to .gitignore, or perhaps a message letting the user know that this is likely a good idea.

Since this file often includes access tokens and the like, one would not want it added to the repo, and this is perhaps something the user should be reminded of when initiating the file through usethis?

**Comment by jennybc** [comment]
It's an interesting idea, but a tough call. Project-level `.Renviron` files are a strange duck and, personally, I rarely use them because they block the effect of my user-level `.Renviron`, which *does* have some tokens in it, among other things. I think a token, especially, should *always* go in user-level `.Renviron` or be handled via a system keyring (which can be accessed via R).

I'm guessing that project-level `.Renviron`, when it exists is meant to "ship" with the project about half the time? And could (should) private/local about half the time?

So if we did this, I think it would have to be an interactive "yes/no" situation.

**Comment by Athanasiamo** [comment]
good points. I very rarely use project-level `.Renviron` but was suddenly in a position where I needed to handle two github PATs, one for gh.com and one for an enterprise solution. As such, the only way I found to get this working decently was to make a project level `.Renviron`  for the enterprise PAT. 

Maybe it could suffice with a message, reminding the user that if they are using it to store credentials it should be placed in `.gitignore`? Though, I am not the best at reading all the messages, at least it would be there? 

An interactive yes/no thing would imo be great. 

I was also tipped about [credentials](https://github.com/r-lib/credentials/) which might provide a better way than using a project level `.Renviron` for the purpose I have currently.

**Comment by jennybc** [comment]
The dev version and next release of usethis will strongly encourage people to get GitHub PATs, at least, **out** of `.Renviron` files and into the Git credential store, instead. And there is explicit GitHub enterprise support. So your immediate problem is definitely already solved.

Now, that doesn't move the needle for other APIs, where people may still use the `.Renviron` solution, but I think that should always be done at the user-level anyway. I think I'll close this for now because most project-level `.Renviron` files need to ship with the project.
