### ISSUE TITLE
Could use_github() fail with a more informative message when not creating the repo?

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#1288]
I had a PAT with wrong scopes so `use_github()` failed with

```r
> use_github()
✓ Checking that current branch is default branch ('master')
✓ Creating GitHub repository 'maelle/tessst'
Error in gh_process_response(raw) : 
GitHub API error (404): 404 Not Found
Message: Not Found
Read more at https://docs.github.com/rest/reference/repos#create-a-repository-for-the-authenticated-user

URL not found: https://api.github.com/user/repos
```

Could the error message when `gh::gh()` fail to create the repo mention the article https://usethis.r-lib.org/articles/articles/git-credentials.html and the functions gh::gh_whoami()` & `usethis::git_sitrep()`? The latter helped me fix my PAT.

**Comment by jennybc** [comment]
It's not so easy, because in general, it's hard to say why any given `gh::gh()` request fails.

I think gh does a pretty good job of exposing everything we know about the error. But you'll notice above it doesn't say anything truly specific, like "check your scopes". This error is coming straight from gh and it would not be practical to intercept every gh error across usethis and attempt to re-issue it with a guess at what's wrong (which is also very difficult to do well).

In contexts where I know the PAT is the problem, I do issue guidance to those 2 resources.

So I think whatever magic allowed you to discover them and fix the PAT is approximately what is supposed to be happening and I'll say the system "worked" 😅

**Comment by maelle** [comment]
This makes sense!
