### ISSUE TITLE
Error when adding files to Git using `use_git()`

### ISSUE THREAD

**Issue by athy9193** [r-lib/usethis#1381]
I am using Windows as operating system with R 4.0.4, `usethis` = 2.0.1, and `devtools` = 2.3.2
I run the following to create a toy R package following this [guide](https://r-pkgs.org/whole-game.html). 
`use_git()` picks up other files, which are not in the project's root folder.

```r
library(devtools)
packageVersion("devtools")
library(tidyverse)
library(fs)

create_package(here::here('foofactors'))

use_git()
```
![image](https://user-images.githubusercontent.com/56498756/109759709-6cc02580-7c28-11eb-88a0-4eeb9284eab0.png)

Also when I selected the option to add all the 113 uncommitted files above, it took awhile to run in Rstudios and produced another error messages as follows.

![image](https://user-images.githubusercontent.com/56498756/109760050-038ce200-7c29-11eb-93fc-21771a068277.png)

**Comment by jennybc** [comment]
This is not something I'm going to be able to reproduce, because I don't have whatever your pre-existing file system state is, which is clearly very important here.

Can you provide runnable code + output (not a screenshot)?

If I have to take a guess, this line suggests a peculiar workflow to me:

```
create_package(here::here('foofactors'))
```

Which translates to 'create a new package HERE, inside my current project'. It smells like we're trying to create one project (a new R package called "foofactors") inside some pre-existing project  (Git repo or RStudio Project). It's not a good idea to nest a Git repo inside a Git repo, for example.

`usethis::proj_sitrep()` gives a "situation report" that might help you shed some light on this.
