### ISSUE TITLE
Should use_github_release() offer to push if needed?

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#1385]
Rather than erroring, as currently.

**Comment by jennybc** [comment]
I've definitely thought about this.

https://github.com/r-lib/usethis/blob/29192cf7e485c7bb29b64d6394aac13909a30880/R/utils-git.R#L336

Kind of related to some discussion in https://github.com/r-lib/gert/issues/65 (which lead to `gert::git_ahead_behind()`, which we are already using).

I think I haven't leaped into action, just because I haven't done a full analysis of the situation where both local and remote have some unique commits. Do we ... attempt to pull with rebase, then push? What if there are merge conflicts?

**Comment by hadley** [comment]
Maybe we could just push (without asking) if there are local commits missing from the remote, but if there are remote commits missing from local we'd still require the user to fix it up.

**Comment by hadley** [comment]
Slightly related — should `usethis::use_dev_version()` also offer to push? It's almost always what you want.
