### ISSUE TITLE
could use_vignette() create files respecting the project's preferred tab width?

### ISSUE THREAD

**Issue by kevinushey** [r-lib/usethis#1434]
See e.g. https://github.com/rstudio/rstudio/issues/9211

Right now, the template uses a default indent of 2 spaces; it would be handy if the indent could be converted based on the currently-configured indentation settings.

This could be potentially read from the project .Rproj file; e.g.

```
EnableCodeIndexing: Yes
UseSpacesForTab: Yes
NumSpacesForTab: 4
Encoding: UTF-8
```

**Comment by jennybc** [comment]
I'm going to close this as #wontfix, since I agree with this comment in the other thread:

> To be honest, I think the "right" solution here is to just turn off auto-detect code indentation by default. While it can be useful, the behavior is confusing and fairly non-apparent for users.

More generally, this is a can of worms I don't want to open, as there are undoubtedly other files where we use a basic template that could potentially violate some wish a user has configured somewhere in their IDE.

I see usethis's file creation as a matter of convenience and there will always be specific users or situations where it's better to do make it yourself or modify the thing we provide.
