### ISSUE TITLE
If `pr_finish()` says branch is associated with multiple PRs, suggest next step

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [r-lib/usethis#1449]
Currently, if a previous PR was merged with the same branch name as the current PR and you run `pr_finish()` usethis gives an error along the lines of:

```
Error: Branch 'pdf' is associated with multiple PRs: '#91', '#84'
```

The appropriate next step seems to be for the user to explicitly state which PR to finish, e.g. `pr_finish(91)`. It would be good if, in addition to the error, usethis showed a message like 

> Pick which PR you want to finish and explicitly mention the number, e.g. `pr_finish(91)` or `pr_finish(84)`.

I should say I was surprised to see this error since the previous PR (and the branch) is long gone from local and remote repo. But suggesting a next step will be helpful nonetheless.

**Comment by jennybc** [comment]
Can you point me towards the repo where this happened, just so I can see the concrete situation?

**Comment by mine-cetinkaya-rundel** [comment]
Sure, the repo is [here](https://github.com/openintrostat/ims) and the two PRs are below:

- https://github.com/OpenIntroStat/ims/pull/91
- https://github.com/OpenIntroStat/ims/pull/84

**Comment by jennybc** [comment]
Note: to self. I think the best move is to raise the possibility suggested by @mine-cetinkaya-rundel, i.e. mention that giving a specific PR number is probably the best plan. Otherwise, I would be signing up to do a lot of analysis, trying to characterize the situation well enough to guess what to do.

**Comment by gadenbuie** [comment]
I recently ran into this as well. Since the goal of `pr_finish()` is to clean up the local repo, could a small amount of analysis help?

- If none of the PRs are open, proceed as normal (possibly with a warning)
- If only one PR is open, proceed as normal possibly with a confirmation
- If more than one PR is open, suggest being specific

**Comment by hadley** [comment]
Can't usethis already handle this automatically in many cases because it caches the PR url? i.e. in my `.git/config` I see:

```
[branch "review-wrapping-apis-vignette"]
	remote = origin
	merge = refs/heads/review-wrapping-apis-vignette
	created-by = usethis::pr_fetch
	pr-url = https://github.com/r-lib/httr2/pull/70
```

**Comment by jennybc** [comment]
I'll try to sort this out in the coming release.

**Comment by jennybc** [comment]
Notes to self: the `pr-url` is not always there and that makes sense. For example the PR in Hadley's example was made by me with `pr_init()` followed by `pr_push()`. The actual PR number is not available to either of those functions, because usethis just opens the browser at a screen which *helps* you open a PR.

Only certain types of subsequent engagement cause `pr-url` to be noted in the branch's config. In fact, I think it's only `pr_fetch()` (which Hadley would have run in the example above).
