### ISSUE TITLE
New GitHub PAT Causing Error in validate_gh_pat(new_gh_pat(x))

### ISSUE THREAD

**Issue by atheobold** [r-lib/usethis#1450]
I accidentally changed my PAT while demonstrating how `gitcreds::gitcreds_set()` works. I then decided the best plan was to regenerate a new PAT. However, upon trying to work through the process of having my PAT recognized, I've come across some major issues. 

When I run `gitcreds::gitcreds_set()`, I select option `2`, replacing the current credentials for https://github.com. I see the following output: 
```
-> Removing current credentials...

? Enter new password or token: NEW_PAT_ENTERED
-> Adding new credentials...
-> Removing credetials from cache...
-> Done.
```

However, when I then run `gh::gh_whoami()`, I get the following output:
``` r
gh::gh_whoami()
#> Error in validate_gh_pat(new_gh_pat(x)): A GitHub PAT must consist of 40 hexadecimal digits
```
<sup>Created on 2021-05-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by malcolmbarrett** [comment]
Have you tried updating gh? See this thread for some suggestions on this error: https://twitter.com/JennyBryan/status/1394824309554630656

**Comment by atheobold** [comment]
@malcolmbarrett -- This completely fixed it! You are a life saver!

**Comment by jennybc** [comment]
For anyone else who stumbles here, a more official document:

https://usethis.r-lib.org/articles/articles/git-credentials.html

**Comment by robo-atheobold** [comment]
@jennybc -- I love the Git Credentials set-up you linked! In fact I reference it *every* time I teach version control. That being said, after spending hours pouring over this and the documentation for the **credentials** and **gitcreds** packages, I'm a bit disappointed that there was no indication that I needed to update **gh**. 

Could a sentence be added to the [Put your PAT into the Git credential store](https://usethis.r-lib.org/articles/articles/git-credentials.html#put-your-pat-into-the-git-credential-store) section, suggesting how to troubleshoot this issue? I'm happy to put in a PR for this change, especially since I can use the `pr_XXX()` functions again!

**Comment by atheobold** [comment]
@jennybc -- I love the Git Credentials set-up you linked! In fact I reference it *every* time I teach version control. That being said, after spending hours pouring over this and the documentation for the **credentials** and **gitcreds** packages, I'm a bit disappointed that there was no indication that I needed to update **gh**.

Could a sentence be added to the [Put your PAT into the Git credential store](https://usethis.r-lib.org/articles/articles/git-credentials.html#put-your-pat-into-the-git-credential-store) section, suggesting how to troubleshoot this issue? I'm happy to put in a PR for this change, especially since I can use the `pr_XXX()` functions again!

**Comment by ijlyttle** [comment]
Sorry to glom onto a closed issue (I had this problem today), but would it be worth updating the minimum version of gh, as a way to avoid the behavior?
 
Currently:

https://github.com/r-lib/usethis/blob/486ed15e93c0d2421a623249441aa0685a124733/DESCRIPTION#L40

**Comment by jennybc** [comment]
@ijlyttle Sure that is a good idea. Not sure how soon usethis will have a release, but that's neither here nor there.
