### ISSUE TITLE
Switch pkgdown site to "auto" development mode

### ISSUE THREAD

**Issue by dmurdoch** [r-lib/usethis#1482]
The pkgdown site at https://usethis.r-lib.org/ shows the devel version number 2.0.1.9000, but doesn't show the status as being an "In-development version", it shows it as a "Released version".  This has led to some confusion on StackOverflow, where someone doesn't understand why the new function `use_import_from()` is not available:  https://stackoverflow.com/q/69159358/2554330 .

**Comment by jennybc** [comment]
This is a fairly common (but not universal) practice across the r-lib and tidyverse organizations, i.e. where the pkgdown site reflects the dev version. It's obviously not ideal, but it also eliminates other downsides, so it's a question of trade-offs.

The unwritten guideline is that we often switch to explicit release + dev site when a package has a "a lot" of use by users who might not pick up on this distinction on their own.

So, to reframe this, I think the point is that perhaps usethis's usage is wide enough to have an explicit release vs. dev site.

**Comment by dmurdoch** [comment]
I don't think I would complain that there is only one site and it is built from the dev version, but I do think it's an issue that it is labelled (in the popup from the version number) as a released version when it hasn't been released.

**Comment by jennybc** [comment]
Oh, I see what you mean. That's not specific to usethis. It seems to be true for all the packages following this regime (e.g. the other examples above), so I think it may be a pkgdown bug. I'll poke around a bit more and presumably open an issue there.

**Comment by jennybc** [comment]
@maelle Do you have any immediate insight into this, given all your experience with pkgdown?

**Comment by jennybc** [comment]
Specifically, we are talking about the tooltip that appears when one hovers over the package version,

<img width="537" alt="Screen Shot 2021-09-13 at 7 38 56 PM" src="https://user-images.githubusercontent.com/599454/133185583-fb53999a-7112-4cfd-b3af-5f9f86be4cfc.png">

**Comment by maelle** [comment]
Interesting. Note that there are quite a few issues around development websites etc in the pkgdown issue tracker ([Dev vs release should be based on env vars](https://github.com/r-lib/pkgdown/issues/943), [Consider readthedocs style handling of multiple versions](https://github.com/r-lib/pkgdown/issues/1373), [Better cross-links between release and dev versions](https://github.com/r-lib/pkgdown/issues/943)) so the current behavior does not seem to be viewed as optimal anyway which you probably know.

* Because usethis' pkgdown config does not indicate a mode, the mode is "release". https://github.com/r-lib/pkgdown/blob/23eb05ceceda1c44573b254dd8b96e92cd91f825/R/development.R#L6
* But you could tweak the tooltip via the [`version_tooltip` parameter](https://pkgdown.r-lib.org/dev/reference/build_site.html#development-mode).

Maybe your point is that the version tooltip message should be different in the default mode?

**Comment by jennybc** [comment]
Apparently several of the downsides (yeah, all those issues you mention and more) to having a development website have recently improved, so I may be willing to give it a try again with usethis. In the past, I had found it caused more problems than it solved, but maybe that's changed.

Yes, I think that tooltip should either be smart enough to say "released" or "dev" version (and be correct) or it should admit it doesn't know and be more vague / descriptive ("package version", "documented version", etc.).

**Comment by jennybc** [comment]
Once pkgdown has its release (whatever's after 1.6.1.9001), I'm willing to try using the "auto" mode for usethis:

```
development:
  mode: auto
```
