### ISSUE TITLE
Function Idea: git_upstream_discover

### ISSUE THREAD

**Issue by jonthegeek** [r-lib/usethis#1629]
If a user forks-and-clones (rather than using `usethis::create_from_github()`), it can be confusing how to set up an upstream. But `usethis::git_sitrep()` can see that the repo is "Type = 'fork_upstream_is_not_origin_parent'", and it knows what it was forked from. While it isn't super difficult to look up the upstream url and run `use_git_remote(name = "upstream", url = upstream_url)`, it's vulnerable to typos.

Would it be desirable to add a function to do that work, and suggest said function in the sitrep? That would be an easier instruction for a user who's trying to do the right thing to follow, rather than going to happygitwithr and figuring out the steps needed to repair their upstream.

I think I could probably PR this if it's desirable.

**Comment by jennybc** [comment]
Sure, in principle, I like providing functions to repair a setup. However, in general, it's hard to repair this situation correctly, which is why so far I haven't done it.

Another equally important part of what `usethis::create_from_github()` does is this:

https://github.com/r-lib/usethis/blob/0d06fae178a34f094f38e6b079755786d2a1620f/R/create.R#L286-L290

where we make sure that the local default branch is tracking **upstream** default branch.

This goes a long way in terms of people swiftly learning to not touch the default branch of a repo they don't own, i.e. to make PRs from a feature branch.

If someone has already "polluted" their local default branch with commits that only they have, setting up this tracking relationship is probably going to lead to even more puzzlement and frustration once they start to push / pull.

Anyway, this is why so far the advice has been that, if you want to use usethis to manage the GitHub aspects of your fork, we want you to use usethis to setup the GitHub aspects of your fork. It's really hard to account for all of the weird initial states people show up with, when trying to fix their setup.

**Comment by jonthegeek** [comment]
I was afraid it was probably more complicated than I was thinking.

Maybe it could check that local is up to date with origin, and origin is up to date with the putative upstream, and only then does the repair?

Ironically enough the person I was trying to help out was *also* using an old version of Rstudio where the helpful pr functions don't work, either, so it turned out to be command-line-time either way, but I've had a fair number of these cases with people not QUITE grokking how to update r4ds.io book club repos (particularly a second time, when they're out of sync with the upstream).

**Comment by jennybc** [comment]
Here's my dilemma:

Is it really worth writing some not-trivial code to repair these? It's not entirely straightforward to analyze their initial state and then make things the way we like.

Having someone start over with `create_from_github(fork = TRUE)` feels so simple and clean to me.

**Comment by jennybc** [comment]
I'm curious about this:

> Ironically enough the person I was trying to help out was also using an old version of Rstudio where the helpful pr functions don't work, either

How does RStudio affect this?

**Comment by jonthegeek** [comment]
The same bug as in #1395. When she tried to `usethis::use_git_remote(name = “upstream”, url = “git@github.com:r4ds/bookclub-tmwr”)`, she got `Error: Function executeCommand not found in RStudio`. And yup, I told her that life would probably be easiest if she just nuked her fork and started over, so I think I agree with your assessment.

**Comment by jennybc** [comment]
Ah, ok, so really vintage RStudio.

It's seems I have beaten you into agreeing with me 😅

Basically, I think there's an awkward phase of Git use and it just can't be eliminated. Given where this person is, something slightly painful has to happen to get back to a happy place and starting over with `create_from_github(fork = TRUE)` seems like a decent solution.

If there's some file they've edited, they should save it in a safe place. After the restart, they can `pr_init()` or create and switch to a proper feature branch and copy the precious file over to make a PR.
