### ISSUE TITLE
Put GitHub md files in .github/

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#165]
Should we?

https://github.com/blog/2111-issue-and-pull-request-templates

https://help.github.com/articles/setting-guidelines-for-repository-contributors/

https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by hadley** [comment]
I think so - at least for `use_tidy_xyz`. 

* ISSUE_TEMPLATE.md
* CONTRIBUTING.md
* CODE_OF_CONDUCT.md
* SUPPORT.md

Only downside is that we can't link directly from README because that will break when release to CRAN (although, come to think of it, they're all `.Rbuildignore`d already, so they won't work anyway).

**Comment by batpigandme** [comment]
Should we have `use_.github` (except a function name that's not that) as an option, or just change the paths for the above-mentioned docs?

**Comment by hadley** [comment]
I think we can just change the paths - we are only creating these for tidyverse packages so we can pick a convention that we like. Will need to add `.github` to `.Rbuildignore` instead of the individual files.

We might also consider having `use_tidy_community()` to create all of them? (And maybe even get rid of the individual functions?)

**Comment by jennybc** [comment]
I plan to deal with this before long (the putting of things below `.github/`).

**Comment by hadley** [comment]
Or maybe just `use_tidy_github()`

**Comment by hadley** [comment]
@jennybc please correct me if I'm wrong, but this is not scheduled this release, right? So maybe @batpigandme can work on it for the next release?

**Comment by jennybc** [comment]
Correct, not a goal for this release.

**Comment by batpigandme** [comment]
✅ it's on my list (you just can't see it here, I assume bc it's out-o'-verse.

**Comment by batpigandme** [comment]
Note to self: have `.github` dir generation working, but running into funky stuff trying to exclude it from `.gitignore`/ add `!.github/*` to `.gitignore` file. Mimic however `.httr-oauth` is added when using [googlesheets](https://github.com/jennybc/googlesheets/blob/9c73e366fd8281f654b11f257988341f8824afc9/inst/shiny-examples/10_read-write-private-sheet/global.R) package with shiny(?)
