### ISSUE TITLE
`use_logo()` asks to overwrite, but won't honor an yes answer

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/usethis#1662]
Using `{usethis}` version 2.1.6.

```
> usethis::use_logo("~/gfx/vector/logos/fluents/fluents-wo-fonts.svg")
Overwrite pre-existing file 'man/figures/logo.svg'?

1: Yup
2: Nope
3: Not now

Selection: 1
Error: [EEXIST] Failed to copy '~/gfx/vector/logos/fluents/fluents-wo-fonts.svg' to '~/sci/code/R/pkg/fluents/man/figures/logo.svg': file already exists
```

**Comment by malcolmbarrett** [comment]
I'm having trouble replicating this, and I'm surprised because `use_logo()` sets `overwrite = TRUE` in `file_copy(): https://github.com/r-lib/usethis/blob/49e3b8886eec1fa36d59317fef41f428c1dbc249/R/logo.R#L31



My attempt at reproducing:

```r
library(usethis)
library(fs)
parent <- dir_create(file_temp())
path <- create_package(path(parent, "mypkg"), open = FALSE)
old_proj <- proj_set(path)
download.file(
  "https://raw.githubusercontent.com/coolbutuseless/minisvg/master/man/figures/logo.svg", 
  path(parent, "logo.svg")
)

download.file(
  "https://raw.githubusercontent.com/coolbutuseless/svganim/master/man/figures/logo.svg", 
  path(parent, "logo2.svg")
)
use_logo(path(parent, "logo.svg"))
use_logo(path(parent, "logo2.svg"))
proj_set(old_proj)
unlink(parent)
```

If you have other details you think might be helpful, please feel free to share. Otherwise you might want to try a good old fashion re-install, re-start, and try again

**Comment by ramiromagno** [comment]
I just installed the development version, and it worked.

It seems that line you mentioned only changed recently: https://github.com/r-lib/usethis/commit/49e3b8886eec1fa36d59317fef41f428c1dbc249

**Comment by malcolmbarrett** [comment]
So it did! I looked at the blame but missed that. Thanks! Looks like this is resolved
