### ISSUE TITLE
Add README.Rmd pre-commit hook during create_from_github?

### ISSUE THREAD

**Issue by jonthegeek** [r-lib/usethis#1667]
When I `use_readme_rmd()`, `usethis` helpfully creates a pre-commit hook to stop me from accidentally committing without rendering that Rmd to md. Would it be desirable to add that (possibly with a confirmation) when I `create_from_github()` and the repo I'm creating has a `README.Rmd`? I think I can probably PR it if it's functionality you'd like.

**Comment by jennybc** [comment]
I've gotten a lot more complaints about this git hook than enthusiasm. In fact, this might be the first time anyone has said anything nice about it :grimacing:

You can explicitly add the hook in your case by executing this bit of code out of `use_readme_rmd()`:

``` r
use_git_hook("pre-commit", usethis:::render_template("readme-rmd-pre-commit.sh"))
```

Because of the complaints, I'm not eager to add the hook silently in even more situations. We could ask if someone wants the hook during `create_from_github()`, but so many people would just be confused by this question. So, this is an interesting idea and I'll file it away. But for now, I'd prefer to stick with the *status quo*.

**Comment by jonthegeek** [comment]
Well I'm sorry to hear that, 'cuz I love that hook! I did the hack to turn it on for mine, at least! I might have to wrap `create_from_github()` in a personal package to get it to work how I want 😊
