### ISSUE TITLE
use_project() should create DESCRIPTION?

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#169]
That way the project can act as a package when needed (i.e. `load_all()`). But we need some field that specifies this is not a package, and update the checks elsewhere.

**Comment by hadley** [comment]
Alternatively, `load_all()` could also look for `.here`

**Comment by jennybc** [comment]
Here's how rprojroot recognizes an R package:

https://github.com/krlmlr/rprojroot/blob/0ec8bf7d70b62201a3749f62100481e15b647550/R/has-file.R#L117

What if we made a DESCRIPTION file that used `Project: foo` instead of `Package: usethis` as the first line?

**Comment by cboettig** [comment]
I agree with @noamross that I'd mostly be worried about breaking compatibility with existing tooling if we replace `Package:` with `Project:`, since that's a major motivation to using DESCRIPTION in the first place.  

- I believe this would break `devtools::install()` as a way to handle the automated install of the project / compendium thing.  Though `remotes::install_deps()` seems to be happy with this (yay!), so maybe it a not a major issue.  

- Looks like this breaks `rcmdbuild;:check()`.  (As you know, you can omit an `R/` dir, put `.Rmd`s in `vignettes` and use `check()` as a way to check for having both valid DESCRIPTION metadata (Author, license, etc) and that the vignette can be rendered.  And can have Travis/Appveyor run these checks with `usethis` setup without additional monkeying around CI config files.  Maybe this setup is a hack but I fits nicely to what I think is a common setup / need for projects.  

- Looks like this switch would also cause `pkgbuild::build()` to fail, though maybe that's okay.

**Comment by hadley** [comment]
@cboettig thanks for the detailed analysis. I agree with your conclusions — there doesn't seem to be much benefit to introducing some sort of special "project" idea that sits partway in between the current conception of a project and a package.
