### ISSUE TITLE
New Feature: create_from_devops()

### ISSUE THREAD

**Issue by jon-brock** [r-lib/usethis#1694]
I work where we cannot use Github, so we use Azure DevOps. I'm in the process of improving workflow with the team and the create_from_github() function would serve all of my current needs except that we don't/can't use Github.

Would it be possible to create a new function called, say, create_from_devops() that does the exact same thing as create_from_github() but using DevOps instead?

I'm digging into the codebase for the function to see if I can create something on my end of things, but I'd say that I'm not quite an expert at building out complex functions (just yet).

I wonder if there is a need from others for something like this.

**Comment by jennybc** [comment]
At this time, we would not merge this into usethis itself, as we've formed a pretty strong opinion over the years and from hard experience that we won't take a big-ish feature that we don't use ourselves. Maintenance of such things becomes a drag because we lack the access and/or motivation to keep it working and updated (and we don't notice when its broken).

Your use case sounds pretty typical as the reason that some folks build an internal usethis-like companion package within their organization. We *do* try to support this sort of activity, i.e. in terms of exporting useful helpers from usethis. So I'd encourage you to pursue your proposal of creating your own `create_from_devops()` by modifying the logic in `create_from_github()`. If you need advice as you go, I recommend: https://r-pkgs.org, https://community.rstudio.com and https://www.rfordatasci.com.

**Comment by jon-brock** [comment]
I'm honored to have a response from THE Jenny Bryan. Thank you for the feedback. I understand the points you made. I will continue to pursue building something out on my end that suits our internal needs.

-Jon
