### ISSUE TITLE
How do I test ui-questions?

### ISSUE THREAD

**Issue by uriahf** [r-lib/usethis#1699]
Hi! 

I'm using ui-questions in my project and I want to test them but I'm not sure how.

While I run the code outside the test environment I get the requried output, but inside the test environment the ui-question does not interact with the required input the same way I want it to.

Is there a good practice for these kind of cases?

```
# Works Fine

set.seed(123)
ui_yeah("Are You Talking to Me?")
1


# Does not work

test_that("Are You Talking to Me Works Fine", {
  
  expect_false(
    set.seed(123)
    ui_yeah("Are You Talking to Me?")
    1
  )

})
```

Thanks!

**Comment by ijlyttle** [comment]
The usethis team will have the definitive answer; could this be useful in the meantime: https://github.com/r-lib/usethis/tree/main/tests/manual ?

**Comment by uriahf** [comment]
Thanks! 

Unfortunately I don't find `ui_nope()` nor `ui_yeah()` in the linked tests, unlike other `ui_*()` functions they require an interactive input.

**Comment by jennybc** [comment]
This issue thread is giving me a powerful feeling of *déjà vu*, but I can't find the previous discussion. So I guess I'm "remembering" this one?

In any case, I have a few answers:

* Literally and directly testing `ui_yeah()` and `ui_nope()` would be our responsibility, not the job of someone using them in their package. Testing other people's functionality usually has more downsides than upsides.
* Some functions go without explicit tests because of the combination of how tricky they are (likely to harbor bugs) and how hard they are to test (hard to test). I feel like `ui_yeah()` and `ui_nope()` are candidates for this. These functions also get exercised intensely enough, in a variety of settings, by our own team even, that I feel pretty confident we'd know by now if they don't behave as intended.

In case you're asking about how to test functions of your own that use `ui_yeah()` and `ui_nope()`, you could mock them, which we apparently do in one test:

https://github.com/r-lib/usethis/blob/8ecb7ab8851faa7d8cc56bfb965e1895c326163e/tests/testthat/test-package.R#L54-L65

I think the *usage* of `ui_yeah()` and `ui_nope()` is the trickiest part and tend to do a fair amount of manual testing whenever I use them. I.e. the hard part is making sure you've wired them into your function in the way you mean to.

**Comment by uriahf** [comment]
Thanks, that was extremely helpful!

Just want to make sure I get it right, I can mock an internal wrapper of `ui_yeah()` but I cannot mock the original `ui_yeah()` because it's not a function from my own package. At least this is what I understood from the [documentation of mockr](https://krlmlr.github.io/mockr/).

**Comment by jennybc** [comment]
Yeah. We used to have a mock function in testthat that "just worked" even for mocking functions in other packages, but apparently it's dark magic was so dark that it was deemed a "bad idea" :sweat_smile:

So yes mockability is sometimes the reason to write an internal wrapper around a function in another package or, even more common for me, for a base function.

**Comment by uriahf** [comment]
All I really care about is having 100% code coverage 😁

I feel like I'm learning alot by writing tests, even if they seem edgy. Thank's again for your great help!
