### ISSUE TITLE
feature request: use_codespaces() function

### ISSUE THREAD

**Issue by k-doering-NOAA** [r-lib/usethis#1703]
With 60 hours of free github codespaces for all github users as of last week, it would be great to provide a usethis function to help users setup their R package repositories for use with codespaces.

Currently, I see there are a few options, including from the [Rocker project](https://rocker-project.org/images/devcontainer/templates.html) and [this r-codespaces repo](https://github.com/jakubnowicki/r-codespaces). There may be other ones I am not aware of.

Potentially other helpful info (although this may be out of scope for usethis::) The team I work with uses R from VS code and also compiled info about configuring vs code to use with R [in this doc](https://noaa-fims.github.io/collaborative_workflow/) and have been using a [devcontainer](https://github.com/NOAA-FIMS/FIMS/tree/main/.devcontainer) (there are some custom options for our project, though, which requires compiling C++ source code).

**Comment by hadley** [comment]
This seems like a good idea, but since we don't currently use codespaces ourselves, it's not a good fit for usethis. Our experience adding usethis features that we don't use personally has generally not been good; it's typically hard to test this sort of feature so without sufficient users, it will tend to bitrot, leading to a negative experience for new users.
