### ISSUE TITLE
Should use_news_md() add a development header if it is a dev version?

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#1708]
Currently, if using `use_news_md()` to create a NEWS file for a package with a development version, one gets the header "package-name package-version". I wonder whether that header should actually be "package-name (development version)"

``` r
withr::local_options(usethis.quiet = TRUE)
temp_dir <- withr::local_tempdir()
dir.create(file.path(temp_dir, "package"))
usethis::create_package(file.path(temp_dir, "package"))

withr::with_dir(file.path(temp_dir, "package"), {
  usethis::use_news_md()
  readLines("NEWS.md")
})
#> [1] "# package 0.0.0.9000"                                     
#> [2] ""                                                         
#> [3] "* Added a `NEWS.md` file to track changes to the package."
```

<sup>Created on 2022-12-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I'd expect the header to be "# package (development version)".

**Comment by malcolmbarrett** [comment]
I think we already do this; does it have to do with the ordering of when you use `use_news_md()` vs `use_dev_version()`?

**Comment by maelle** [comment]
This is a brand-new package so its dev version comes from the defaults/Rprofile defaults. I agree that for later development, things already work like you say.

**Comment by maelle** [comment]
So to clarify, my issue is only for brand-new packages with a dev version number. :slightly_smiling_face:

**Comment by malcolmbarrett** [comment]
I've gotten away from putting it in until after my first release (based on the order of `use_release_issue()`, so it hasn't been a problem for me.

That said, it might make sense for the default template to assume it's a dev version upon adding it

**Comment by hadley** [comment]
I think it might be slightly better for to call `use_news_md()` earlier in the release process (i.e. before initial submission) and if the current version is 0.0.1, the bullet should be "Initial submission".

**Comment by DavisVaughan** [comment]
We now have a bullet to call `use_news_md()` very early in the `use_release_issue()` process for both a new package release and an existing package release (if we detect there is not currently a NEWS file).
- https://github.com/r-lib/usethis/blob/b4b86233821016a58fc529f1e90e017512b4ca72/R/release.R#L93
- https://github.com/r-lib/usethis/blob/b4b86233821016a58fc529f1e90e017512b4ca72/R/release.R#L114

We now need to make a change where `use_news_md()` should insert `(development version)` rather than the actual version if `proj_version()` looks like a development version. This way `use_version()` can detect it and update it accordingly.

For a new package, that means it should end up looking like:
- `use_news_md()` is called and inserts `# pkg (development version)`
- `use_version("minor")` is called before release and updates that to `# pkg 0.1.0`

The only weird situation I can imagine here is if you don't have a NEWS file and your package version is currently sitting at something like `0.2.0`, which looks like a "production" version. In this case, I imagine we should just put `# pkg 0.2.0` when creating the NEWS file, which is the current behavior.
