### ISSUE TITLE
Helper to revert `use_pipe()` and update package with base pipe

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/usethis#1709]
It might be nice to have a helper to move a package from using the magrittr pipe to base pipe. 

Such a function would:

- Undo what `use_pipe()` does
- Replace instances of `%>%` with `|>` in code, vignettes, and tests
- Suggest that the test suite is run to check the impact of the changes

**Comment by hadley** [comment]
Would also need to add a dependency on R 4.1.  I'm also not sure you'd want to remove the effects of `use_pipe()` as that might break existing code.

But I'm sceptical it's possible to do this automatically. All we can really do is a global search and replace for `%>%` and I don't think there are particularly advantages to scripting that, since you're likely to still have to do cleanup afterwards.
