### ISSUE TITLE
`create_from_github()` should wait a few seconds before trying to clone after forking

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/usethis#1755]
I consistently get this issue when I use `create_from_github()` _the first time_.

```r
> usethis::create_from_github("mpallocc/auto-go", "~/Desktop/r/playground/packages/")
✔ Setting `fork = TRUE`
✔ Creating '/Users/davis/Desktop/r/playground/packages/auto-go/'
✔ Forking 'mpallocc/auto-go'
✔ Cloning repo from 'git@github.com:DavisVaughan/auto-go.git' into '/Users/davis/Desktop/r/playground/packages/auto-go'
Error in libgit2::git_clone : 
  remote error: access denied or repository not exported: /1/nw/1d/b2/2d/439104554/594071937.git
```

It always works the second time.

I asked Jeroen and he said it takes a few seconds for a new repo to become clonable.

He pauses for 10 seconds in r-universe code here:
https://github.com/r-universe-org/setup-universes/blob/712f956acd73f878a0df0a4c8e0cb657019831e5/R/setup.R#L94-L100

I vote we do something similar, maybe pausing for 5 seconds and seeing if that is enough? Probably would be good to also notify the user that we are pausing for a second to let the repo become clonable.

**Comment by jennybc** [comment]
We have `Sys.sleep()` in various GitHub-y functions and others have come and gone, as necessary. So, yes, this is a phenomenon usethis has some history with.

> I consistently get this issue when I use `create_from_github()` the first time.

As for that, I think it's because the first attempt creates the fork, so the second time, we aren't actually creating a fork. We send that request, but GitHub sees that you already have a fork and returns the info for that repo, which was already there and waiting.

I'm hesitant to reflexively add a 5 or 10 second wait here. Have you been seeing this for a long time and consistently? I think it would be better to have a shorter wait or to handle with some sort of retry.

**Comment by malcolmbarrett** [comment]
I never thought much of this, as it doesn't happen to me often, but I've seen this, too. A shaky recollection of when seems to match this pattern. Could we instead look for this specific error and then delay retry?

**Comment by DavisVaughan** [comment]
It has only started happening in the last week or so, but is very consistent now
