### ISSUE TITLE
`use_release_issue()` bullet for `Add link to blog post in pkgdown news menu` isn't in a useful order

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/usethis#1761]
Pulling from dplyr's 1.1.0 release bullet, we had

```
Wait for CRAN...

* [x] Accepted :tada:
* [x] `git push`
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version()`
* [x] `git push`
* [x] Finish blog post
* [x] Tweet
* [x] Add link to blog post in pkgdown news menu
```

That last bullet doesn't seem to be in the right place because by that point you are already on the "dev" pkgdown site, so you won't ever see a link to that release's blog post until the _next_ release of the package

**Comment by DavisVaughan** [comment]
It might be a bit of a chicken and egg problem?

i.e. when you push the commit that bumps to a new released version (which rebuilds the released pkgdown site), you want that to link to the blog post, which means the blog post needs to be released first.

But when you write the blog post, you often want to link to the newly released version of the pkgdown site, which means the pkgdown site needs to be updated first.

**Comment by jennybc** [comment]
🐔 🐣 🥚

**Comment by ateucher** [comment]
I think the short time that people get a 404 from the blog post link in the pkgdown site is probably worth avoiding the pain of updating an already-published release version of the pkgdown site? 

If one calls `use_version(push = TRUE)`, that's the step that will create the release version of the pkgdown page, in which case the "Add link to blog" bullet should go before that. If one does `use_version(push = FALSE)`, then then the bullet should go between "Accepted :tada:" and `usethis::use_github_release()` (Which now pushes automatically). What are we expecting to be the norm? I'm guessing the latter, since `use_version(push = FALSE)` is the default...
