### ISSUE TITLE
Feature request: `use_example()`

### ISSUE THREAD

**Issue by ngreifer** [r-lib/usethis#1814]
I love this package and it has helped me so much in package development. I have a feature request that I don't think would be too hard to implement but I am struggling to make it work myself.

In the vein of `use_test()`, which creates a test file for `testthat`, I'm imagining `use_example()`, which 1) creates the folder `inst/examples` if it does not exist (possibly giving the user the option to choose a name), 2) creates an R script `ex-foo.R` in that folder corresponding to the R script currently open (like `use_test()` does), and 3) adds `#' @example inst/examples/ex-foo.R` to the `roxygen2` comments for function `foo()`. 

Because writing examples in `roxygen2` blocks can be a little hard because it lacks some of the capabilities that simply writing R code in a script has, the `#' @example {file.R}` functionality makes it easy to write an example in a separate script. `use_example()` would be a shortcut function to facilitate that process and make it easier to use. Thank you for considering.

**Comment by rossellhayes** [comment]
I've been using a `use_example()` function in my own workflow for a while, so I figured I'd open a PR and contribute it here in case it would be helpful: #1815.

There are a few differences between my implementation and this feature request:
- My implementation creates files in `man/examples` rather than `inst/examples`.
- My implementation prefixes file names with `example-` rather than `ex-`.

I'd be happy to discuss the pros and cons of those decisions and adjust my PR to match the consensus!

**Comment by ngreifer** [comment]
Thank you Alex! This looks awesome!

**Comment by jennybc** [comment]
This seems like an interesting idea, but we (usethis maintainers, tidyverse/r-lib team) don't currently use external examples ourselves. Our experience adding usethis features that we don't use personally has not been good. These features are especially vulnerable to bit rot, since we won't notice problems in a timely manner and we lack motivation and context when work is needed. This can then lead to a negative experience for new users.

Thanks again for the suggestion, but we've learned everyone is better off if we identify a lack of fit in advance.
