### ISSUE TITLE
ui_oops() breaks testthat::expect_error()

### ISSUE THREAD

**Issue by francisbarton** [r-lib/usethis#1819]
If you use usethis::ui_oops to wrap your error messages, it seems like it maybe doesn't pass the error message through properly?

So if you are looking for a particular custom error message when testing, ui_oops will not return the expected message.

``` r
is5 <- function(x) {
  assertthat::assert_that(is.numeric(x), msg = "x must be numeric")
  x == 5
}

testthat::expect_error(is5("a"), "x must be numeric")

is6 <- function(x) {
  assertthat::assert_that(is.numeric(x),
    msg = usethis::ui_oops("x must be numeric"))
  x == 6
}

testthat::expect_error(is6("a"), "x must be numeric")
#> ✖ x must be numeric
#> Error: `is6("a")` threw an error with unexpected message.
#> Expected match: "x must be numeric"
#> Actual message: "x is not a numeric or integer vector"
```

**Comment by jennybc** [comment]
The expectation is wrong and therefore it's failing for legitimate reasons. The error message really is "x is not a numeric or integer vector". That's because `ui_oops()` returns `NULL` and you are getting assertthat's default message.

`ui_oops()` exists for its side effect, which is to print something to screen, not to return (formatted) text. I think it's just not appropriate to use `ui_oops()` as the `msg` in `assertthat::assert_that()`.

``` r
is6 <- function(x) {
  assertthat::assert_that(is.numeric(x),
    msg = usethis::ui_oops("x must be numeric"))
  x == 6
}

is6("a")
#> ✖ x must be numeric
#> Error: x is not a numeric or integer vector

x <- usethis::ui_oops("x must be numeric")
#> ✖ x must be numeric
x
#> NULL
```

<sup>Created on 2023-04-10 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>
