### ISSUE TITLE
FR: use_test_helper()

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#1822]
I really enjoy using `use_test()` and `use_r()`, but was wondering whether there could be an equivalent for creating a `tests/testthat/helper-` file? (I didn't find any related issue but might have missed one :sweat_smile:)

**Comment by olivroy** [comment]
I agree. I think it may be a little bit less straightfoward than the other 2.

Should there be an option for a generic test helper `"tests/testthat/helper.R"`, vs file specific test helper?

**Comment by olivroy** [comment]
I made a little sketch. I don't really like that the default isn't consistent with the default of `use_test()`, but also I think that having a helper file for each test file by default seems a bit overkill.

```r

#' @rdname use_r
#' @export
#' @param scope if global, creates "tests/testthat/helper.R", otherwise creates
#'   "tests/testthat/helper-{name}.R
use_test_helper <- function(name = NULL, scope = c("global", "file"), open = rlang::is_interactive()) {
  if (!uses_testthat()) {
    use_testthat_impl()
  }
  scope <- arg_match(scope)

  if (scope == "global") {
    path <- path("tests", "testthat", "helper", ext = "R")
  } else {
    path <- path("tests", "testthat", paste0("helper-", compute_name(name)))
  }

  edit_file(proj_path(path), open = open)
  ui_bullets(c(
    i = "Run {.run devtools::load_all()} to load objects from helper files in
         your environment."
  )
  )
  invisible(TRUE)
}
```

**Comment by jennybc** [comment]
I'm generally on board, so happy to see this in PR form. I'm not sure the `name` and `scope` arguments are quite right yet. I don't have great vocabulary for `stuff` yet, but clearly we want to make it easy to ask for `helper.R` versus `helper-stuff.R`. I think 1 argument is enough. "Suffix" almost captures it, but it's not perfect 🤔

**Comment by jennybc** [comment]
Starting to actually think about this now, including the PRs #1978 and #1990.

Some high-level thoughts (informed by a quick consult with @hadley too):

* Test helper files don't have the same tight coupling as `R/whatever.R` and `tests/testthat/test-whatever.R`. We think of a test helper file as belong to the _package_ not to a specific R or test file. Which is why the default is a plain old `tests/testthat/helper.R`.
* So I definitely don't see the need to support the file creation/opening functionality that `use_r()`/`use_test()` for helping you manage the file pair.
* In terms of what that means for `use_test_helper()`, that just leaves the initial creation of a helper file. Which might not really justify adding a new function 🤔

**Comment by olivroy** [comment]
it would also be useful to access it to add new functions to it.

I would understand that it may not be worth a new function, but typing `edit_file("tests/testthat/helper.R")` is a bit clumsy. 

In terms of promoting good workflow, it would be a + too., 

I find test helpers are life savers for efficient testing workflows (as they are loaded with `load_all()`, but they are not used that much in the wild.

But otherwise, feel free to close and I will just add this to my .Rprofile/

```r
use_test_helper <- function() usethis::edit_file("tests/testthat/helper.R")
```
Looking at it, it's true that it doesn't seem worth the effort. Maybe adding this example to the documentation of `edit_file()` would be a good idea?

**Comment by jennybc** [comment]
I'd be happy to review a small PR with a small function that helps to create (and open) a test helper file, in the right place, with a good name (defaulting to `"tests/testthat/helper.R"`). The only added feature could perhaps be a way to create `"tests/testthat/helper-foo.R"`, if it's the kind of package with multiple helper files. Let's leave this one available for tidyverse dev day.
