### ISSUE TITLE
`use_cpp11()` should not add `SystemRequirements: C++11`

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/usethis#1824]
Since CRAN no longer wants this and we have begun removing it as we update packages.

I am 90% certain this is correct, but am still waiting on confirmation of the fact that packages using cpp11 don't need this anymore.

**Comment by jennybc** [comment]
I haven't gotten an official answer on this, but I'm fairly convinced I've made the right move.

**Comment by stephematician** [comment]
That seems like the right move. Looking at the current advice on Writing R Extensions ([Using C++ Code](https://cran.r-project.org/doc/manuals/R-exts.html#Using-C_002b_002b-code)), would it be possible to state the standard in src/Makevars[.win/.ucrt]?

They state that setting `CXX_STD=CXX14` is preferred (to ensure longer term portability) and is potentially supported as far back as R 3.4.0.

**Comment by DavisVaughan** [comment]
I don't think that is really preferred in the longterm because that locks you in to C++14 even if the code works on C++17 and above. I had `CXX_STD=CXX11` in one of my packages and was forced to remove that too. So putting `CXX14` in there is just asking for the same problem to happen a few years from now, unless you _really_ require just C++14 and nothing else

**Comment by stephematician** [comment]
True. And I'm not 100% on board with the Writing R Extensions advice, due to the same reasoning. I guess the question any package writer has to ask is - what is more likely to happen first; the build breaks because of incompatibility with the (latest) default standard, or the build breaks because the compiler drops 'support' for a standard enforced via CXX_STD? Happy either way, really.
