### ISSUE TITLE
Make `use_coverage()` add covr to `Config/Needs/coverage` rather `Suggests`

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/usethis#1844]
Currently, `use_coverage()` adds covr to `Suggests`. 

Since covr is only used during package development, I would prefer to include it in `Config/Needs/coverage`. I believe this is consistent with the fact that, e.g., rcmdcheck is not listed in `Suggests` either. Additionally, the [`test-coverage` workflow](https://github.com/r-lib/usethis/blob/e05947f0e49244d7dcb13105a48e32718eb59db5/.github/workflows/test-coverage.yaml) already installs covr, as well as any dependency listed in `Config/Needs/coverage`.

**Comment by jennybc** [comment]
I haven't done the research you have, but what you're saying and proposing sounds reasonable. I think `use_coverage()` came before the GHA era or, at least, much earlier in it. A PR would be welcome so we can have a concrete discussion. It's interesting to compare this to how `use_pkgdown()` / `use_pkgdown_github_pages()` work.

(I don't think it's quite parallel with rcmdcheck because that is just a specific way to run `R CMD check`. Whereas, if you're computing test coverage, you'll be using covr.)
