### ISSUE TITLE
withr::local_dir() vs withr::defer ... set_wd()

### ISSUE THREAD

**Issue by jonthegeek** [r-lib/usethis#1895]
https://github.com/r-lib/usethis/blob/467ff57f92afb34878dc411c46e3f0de029ceea4/tests/testthat/helper.R#L69-L76

Does this pre-date `withr::local_dir()`, or is there a reason it's done more explicitly here? I copied this concept for a package-creating package, without noticing that `withr::local_dir()` exists and is cleaner.

https://github.com/r-lib/usethis/blob/467ff57f92afb34878dc411c46e3f0de029ceea4/tests/testthat/helper.R#L38 is also related, in case it's fine to update this to local_dir. I can PR if you'd like.

**Comment by jennybc** [comment]
I *think* it's that I wanted to schedule that `ui_done()` to occur at the same time as restoring the working directory.

Developing `create_local_thing()` was a gradual and somewhat painful process. And, yeah, a lot of ideas and maybe even tools have matured since that got written. So it's believable and that I would write it differently if I started right now. But I plan to leave it alone until/unless there's some other reason to fiddle with it.

**Comment by jonthegeek** [comment]
That makes sense! FWIW, I switched it out in my version, and the tests remained happy, and this also stayed happy:

```
set_state_inspector(function() {
  list(
    wd = getwd(),
    proj = usethis::proj_get()
  )
})
```

**Comment by jennybc** [comment]
Nice! So I think `local_dir()` could be used here, in terms of functionality, but I'm not going to touch this load-bearing helper until there is some other reason to do so.

**Comment by jonthegeek** [comment]
I really appreciate the modeling of "know when to say no" behavior! Thanks for everything 😊
