### ISSUE TITLE
Include additional parameters for parameter for `use_github_release()`

### ISSUE THREAD

**Issue by jmbarbone** [r-lib/usethis#1926]
Request to include additional parameters can be safe

https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release

- `prerelease = FALSE`
- `generate_release_notes = FALSE` (which will _append_ to info in `NEWS.md`)

Seems like these can be safely placed in the `gh()` call (and didn't give me any issues when playing around with it)

https://github.com/r-lib/usethis/blob/709f82582eb3be6ed1cfea459e4e9de8d25ae553/R/release.R#L266-L273

**Comment by jennybc** [comment]
This seems like an interesting idea, but we (usethis maintainers, tidyverse/r-lib team) don't currently use prereleases much ourselves and our use of human-facing NEWS bullets for the release notes is an intentional choice. Our experience adding usethis features that we don't use personally has not been good. These features are especially vulnerable to bit rot, since we won't notice problems in a timely manner and we lack motivation and context when work is needed. This can then lead to a negative experience for new users.

Thanks again for the suggestion, but we've learned everyone is better off if we identify a lack of fit in advance.
