### ISSUE TITLE
`use_tidy_thanks()` does not return markdown string

### ISSUE THREAD

**Issue by chartgerink** [r-lib/usethis#1998]
Thank you for the amazing package 🙏 I open this issue with much love for the work you do!

We have automated release blogs in our project, and want to now add an acknowledgements section into our markdown files. 

We are running into the issue that the function is only returning a vector of GitHub handles, whereas we would like to include the markdown that is copied to the clipboard when running the function. 

So for example, we run and get the following

```
x <- usethis::use_tidy_thanks('epiverse-trace/simulist')
x
[1] "Karim-Mane"          "github-actions[bot]" "joshwlambert"  
```

Whereas we would like to get this output instead

```
[&#x0040;github-actions[bot]](https://github.com/github-actions[bot]), [&#x0040;joshwlambert](https://github.com/joshwlambert), and [&#x0040;Karim-Mane](https://github.com/Karim-Mane).
```

I tried adjusting it directly in the code locally, and all tests pass on my end when I return the code snippet. I wanted to ask here, would you be open to a pull request that would provide an option to return the markdown string in `use_tidy_thanks()`? 😊

**Comment by jennybc** [comment]
If I remembering correctly, the current behaviour is intentional. Basically, we've got the contributor data in two forms: a normal character vector and formatted markdown. So we send the formatted markdown out as a code snippet *which should also put it on the clipboard* and then invisibly return the character vector. I think our typical use of this is when writing our blog posts and, when you're authoring the post, you're in the blog repo. So it makes sense to go execute `use_tidy_thanks()` in the relevant package repo, then paste the result into the draft blog post. So, it's a very interactive workflow for us.

Anyhow, maybe this context is useful for how we got where we are.

**Comment by jennybc** [comment]
I think the first step (and maybe only step) is to work out the incantation that allows your usage without any changes in usethis.

I see two approaches:

```
x <- capture.output(
  usethis::with_project(
    "~/rrr/reprex",
    use_tidy_thanks()
  ),
  type = "message"
)
```

plus some fiddling with `x` to get the line you want.

Or you just inlining this bit:

```
contrib_link <- glue("[&#x0040;{contributors}](https://github.com/{contributors})")
```

You can still make a PR, but I can't just change the return value of `use_tidy_thanks()` for fear that someone else has already done some programmatic work around the _status quo_. What change do you have in mind and would it be a breaking change for other people?
Perhaps some combination of `usethis::with_project()` and

**Comment by chartgerink** [comment]
You're completely right - I apologize for wasting your time on this. I completely overlooked that it is trivial to transform this output into what I need.

Thank you for your patience with me 💛
