### ISSUE TITLE
feat: diffify badge

### ISSUE THREAD

**Issue by csgillespie** [r-lib/usethis#2018]
Would you be interested in a PR for creating a diffify badge?

<a href="https://diffify.com/R/usethis" target="_blank"><img src="https://diffify.com/diffify-badge.svg" alt="The diffify page for the R package usethis" style="width: 70px; max-width: 100%;"></a>

If so, I'm happy to make a PR

**Comment by jennybc** [comment]
I have not heard of diffify before (and am recovering from recent-ish badge work related to codecov changing it's URL / badge image structure). Standard response in this situation incoming ...

This seems like an interesting idea, but we (usethis maintainers, tidyverse/r-lib team) don't currently use *diffify* ourselves. Our experience adding usethis features that we don't use personally has not been good. These features are especially vulnerable to bit rot, since we won't notice problems in a timely manner and we lack motivation and context when work is needed. This can then lead to a negative experience for new users.

Thanks again for the suggestion, but we've learned everyone is better off if we identify a lack of fit in advance.
