### ISSUE TITLE
Funky bullet in `git_sitrep()`

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#2034]
The line for "Default Git protocol" is wonky. I suspect we need to suppress the message 'i Defaulting to "https" Git protocol'.

```
> git_sitrep()

── Git global (user) 
• Name: "Jenny Bryan"
• Email: "jenny.f.bryan@gmail.com"
• Global (user-level) gitignore file: [~/.gitignore_global](vscode-file://vscode-app/Applications/Positron.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#)
• Vaccinated: TRUE
• Default Git protocol: ℹ Defaulting to "https" Git protocol. "https"
• Default initial branch name: "main"
```

**Comment by thomascwells** [comment]
Working on this at tidy-dev-day. Some notes while working on it: 

- That line in `git_sitrep()` comes from the `git_protocol()` function. 
- I was not immediately able to reproduce the issue. I believe that is because I have a user-level .Rprofile setup with this option set: 

```r
options(
  usethis.full_name = "Thomas Wells",
  usethis.protocol = "https",
  ...
)
```
- I am able to reproduce the issue if I launch R from the (bash) terminal with `R --no-init-file` or use `options("usethis.protocol" = NULL)` after my session is loaded
- The funky bullet only shows up the **first time** you run `git_sitrep()` or `git_protocol()` in a session. This is because the function call sets the option for the remainder of the session.
