### ISSUE TITLE
GitHub connectivity

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#214]
Organizing various thoughts and issues around GitHub. Won't all be completed in v1.2.0 but this should make it easier to discuss and plan.

You = the usethis user
Them = anyone else, but often an instructor, collaborator, other dev
Here's the relevant universe of Git repos (them vs. you * GitHub vs. local):

<img width="638" alt="them-you-github-local" src="https://user-images.githubusercontent.com/599454/35029450-cf98e0e0-fb0f-11e7-87e1-ec9daed91a09.png">

How usethis functions help to make the necessary connections:

<img width="267" alt="screen shot 2018-01-16 at 10 53 34 pm" src="https://user-images.githubusercontent.com/599454/35029515-23402f0a-fb10-11e7-8cf1-341d79eb95e6.png">

`create_from_github(repo = THEM_GITHUB, destdir = YOU_LOCAL_PARENT_DIR, fork = TRUE, ...)`
TODO: add THEM_GITHUB as remote `fork-origin` of YOU_LOCAL repo

<img width="243" alt="screen shot 2018-01-16 at 10 56 09 pm" src="https://user-images.githubusercontent.com/599454/35029584-7cc997c8-fb10-11e7-9b06-9efef1694e8b.png">

`create_from_github(repo = THEM_GITHUB, destdir = YOU_LOCAL_PARENT_DIR, fork = FALSE, ...)`

<img width="117" alt="screen shot 2018-01-16 at 10 56 45 pm" src="https://user-images.githubusercontent.com/599454/35029603-926a9244-fb10-11e7-9462-2a0408943be7.png">

`create_from_github(repo = YOU_GITHUB, destdir = YOU_LOCAL_PARENT_DIR, fork = FALSE, ...)`

<img width="83" alt="screen shot 2018-01-16 at 10 57 32 pm" src="https://user-images.githubusercontent.com/599454/35029631-ab7c9034-fb10-11e7-9b9d-99389a833b8e.png">

`use_github(...)`

**Comment by jennybc** [comment]
> Essentially, I want to go from box 1 to box 1 (or equivalently, box 2 to box 2).

Is there even an existing way to do that in the browser or via the API? Create GitHub repo A from GitHub repo B without forking?

I do understand your goal btw.

**Comment by cboettig** [comment]
No, there's no way to do this in the GitHub API.  My understanding is that was a major reason why GitHub Classroom was created in the first place, it provides a web API to do exactly this (and little else). 

BTW, I just noticed `usethis::use_course()`, `use_course()` + `use_github()` is almost exactly what I'm looking for (I think).  I'd just like to see `use_course()` handle repo names (or at least repo urls) directly instead of only zips; and perhaps the use of the term `course` is too narrow.  (For instance, following the model suggested by GitHub Classroom, I've found it helps if I have a separate repo for each project, rather than one big course repo.  Likewise I use this same workflow with my lab group, starting students off with a template repo that has travis set up to test that any .Rmd renders successfully.  So I think of this more as `use_template` than `use_course`).

**Comment by jennybc** [comment]
OK I've really read this now. Yes, let's keep hammering it out ... but after today's release. You want a few things that are not trivial: the copy-that's-not-a-fork, repo name flexibility, and remote handling.

As for your `use_git()` glitch, yeah usethis has no way of knowing about the directory rename. You could raise this in a separate issue, but I'm not sure we'd "fix" it. You can just insert a `proj_set()` right after your `file.rename()`. Once we can use [fs](https://github.com/r-lib/fs) for file system stuff, you could imagine `proj_set(file_move(..., ...))`.

**Comment by cboettig** [comment]
Thanks, sounds like a plan!

Re `use_git()`, thanks for the `proj_set()` pointer; the behavior there was a little opaque to me.  I had tried deleting the `.Rproj` after renaming the file, and couldn't think of where else it was able to get the old path from instead of the new path. A quick dig showed it was getting the path from `proj_get()` but looking at the R code for that function told me nothing about where it reads the path from.  Reading the documentation as a last resort I see it was coming from the DESCRIPTION in my case, which I guess assumes package name should match the repo name).  I follow the logic here but still feels a little ick that `use_git()` would tell me I'm not in a git repo when I am in a git repo but simply have a DESCRIPTION (or some hidden `.here` file) that has an outdated path...

**Comment by jennybc** [comment]
It occurs to me that `use_course()` might actually be useful to you, until the perfect functionality exists usethis (or elsewhere). Because it allows you to grab the current contents of a template Git repo w/o making a fork, getting history, or acquiring remotes. Worth considering.

**Comment by cboettig** [comment]
Indeed it is! https://github.com/r-lib/usethis/issues/214#issuecomment-358394821

**Comment by jennybc** [comment]
D'oh.

**Comment by mine-cetinkaya-rundel** [comment]
Grabbing contents without the git history is nice, and a positive above GitHub Classroom. With GitHub Classroom students see history of the repo from before they created their copy, and I personally find that undesirable.
