### ISSUE TITLE
remote URL badly formed when using create_from_github()

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/usethis#222]
When I ran

```R
create_from_github("ijlyttle/happy-git-with-r", destdir = "path/on/my/computer")
```

everything else worked as expected, but the remote that got set up looked like this:

```
$ git remote -v
origin  git://github.com/ijlyttle/happy-git-with-r.git (fetch)
origin  git://github.com/ijlyttle/happy-git-with-r.git (push)
```

I had a look at the [code](https://github.com/r-lib/usethis/blob/e253a790684ae2a6f6be30a6b009e301304ba74d/R/create.R#L109) for `create_from_github()`, and I don't see that **usethis** is setting a remote, so I think the issue might be in `git2r::clone()`.

To be sure, this is not urgent as the remote can be reset by hand. 

@jennybc: whenever you might have some time, could I impose on you for a sanity check on this before I raise an issue at git2r?

**Comment by jennybc** [comment]
I consider this a subset of #215 (`create_from_github()` should share many arguments with `use_github()`).

I noticed this odd choice of URL when making the minimal repairs necessary to get `create_from_github()` working slightly better for this release (da1a8c2586646e8da75be530251aad0931df6298). Yeah, it should be using either the HTTPS or the SSH URL instead of this, whatever it is. But to do that, you need to know about HTTPS vs SSH, which the current function does not. So I decided to leave it alone and get this release out the door.

I assume `create_from_github()` will acquire some remote setting logic somewhat inspired by `use_github()`, e.g. 

https://github.com/r-lib/usethis/blob/e253a790684ae2a6f6be30a6b009e301304ba74d/R/github.R#L142-L151

If I've understood you correctly, I'll leave you to close this. And if I haven't, let's keep talking.

**Comment by ijlyttle** [comment]
Thanks! I think we're on the same page - happy to close in favor of #215 (and to pitch-in there, when the time comes).

**Comment by jennybc** [comment]
> Yeah, it should be using either the HTTPS or the SSH URL instead of this, whatever it is.

```
$ git remote -v
origin  git://github.com/ijlyttle/happy-git-with-r.git (fetch)
origin  git://github.com/ijlyttle/happy-git-with-r.git (push)
```

I finally figured out what "this" is. In Git in Practice, it explains that Git can communicate with a remote via HTTP, SSH, or *its own protocol* and this `git://`- style of remote URL is given. So, it's still definitely not what we want, but at least the mystery is solved.
