### ISSUE TITLE
CI in setup article

### ISSUE THREAD

**Issue by maelle** [r-lib/usethis#280]
Would it make sense to mention creating Travis and Appveyor accounts in the :gem: setup article :gem: ? What about the code coverage sites? I actually don't even remember if one needs to _create_ an account for all these services, I think so even if it uses the GitHub credentials?

**Comment by jennybc** [comment]
I think this is beyond the scope of the setup article.

I also ... feel like I've never explicitly setup accounts with CI services? I think my relationships with them piggyback on my GitHub identity. That is all a distant memory now.

I really want the setup document to focus on Git and GitHub because I think that's what target audience will want out of usethis and they'll want it to "just work".

Closing for now but we re-examine if people's usage suggest this is a stumbling block.
