### ISSUE TITLE
use_tidy_thanks()

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#296]
Name still up for discussion.

Function to look at GitHub repo and extract usernames of contributors, optionally since a specific date. Basically polish up the code snippet we've been using to create the Acknowledgement section of [tidyverse.org blog posts](https://www.tidyverse.org/articles/) (scroll to end of this one for an example: https://www.tidyverse.org/articles/2018/02/usethis-1-3-0/

Upgrade we want: ability to manually record that someone belongs in acknowledgements, even if they won't get caught in the basic automated GET of, e.g., people opening issues or PRs.

A snippet we have used with gh v3 API:

``` r
x <- gh::gh(
  "/repos/r-lib/usethis/issues",
# initial usethis post did not include this section, let's get 'em now  
#  since = "2017-11-21",
  state = "all",
  .limit = Inf
)
users <- sort(unique(purrr::map_chr(x, c("user", "login"))))
length(users)
clipr::write_clip(glue::collapse(glue::glue("[\\@{users}](https://github.com/{users})"), ", ", last = ", and "))
```

A gist where @jimhester is experimenting with the newer graphql API for various tasks: https://gist.github.com/jimhester/9f3339f2a0ca81f7027e963356b80008

**Comment by maelle** [comment]
@sckott did something similar for a README and I packed his code in https://github.com/maelle/ghrecipes (using the V4 API via `ghql` and `jqr`) as an "iterate" helper function and a "get_issue_authors" functions (it works because the query in "get_issue_authors" only has one occurrence of "hasNextPage" and "cursor"), but it only extracts all issue openers at the moment, not at a given date. 

Before seeing this issue the bottom of your article had made me think about the "get_issue_authors" function. :-)
