### ISSUE TITLE
Ensure usethis functions do not create R patchlevel dependencies

### ISSUE THREAD

**Issue by jimhester** [r-lib/usethis#315]
CRAN recently added a new WARNING about packages with R patchlevel dependenecies, see https://github.com/r-lib/devtools/issues/1742. Unfortunately currently devtools / usethis generate these dependencies by default. We should ensure all usethis functions only create minor version dependencies, e.g. `R (>= 3.4)` rather than `R (>= 3.4.3)`

**Comment by jennybc** [comment]
I haven't scoured usethis yet, but so far it's not apparent to me how usethis -- what, via `create_package()`? -- is promoting R patchlevel dependencies. I will look harder when dealing with some other issues around minimum versions for packages. But if you already know more about where the problem lies, please speak up.

**Comment by jimhester** [comment]
Actually I think this is fixed by 7937594c, so we can close it
