### ISSUE TITLE
Feature request: use_rcpp_armadillo() and use_rcpp_eigen()

### ISSUE THREAD

**Issue by alexpghayes** [r-lib/usethis#421]
RStudio provides package templates for packages that use `Rcpp` and `RcppArmadillo`, but if you decide to use `RcppArmadillo` mid-project it can be a bit tricky to remember what goes where. I use `RcppArmadillo` infrequently and can never remember the setup that needs to happen. Having helpers

- `use_rcpp_armadillo`
- `use_rcpp_eigen`

would be incredibly convenient.

**Comment by duckmayr** [comment]
I came to open an issue on this also. I went ahead and wrote up these functions (and tests for them), and I'm ready to open a pull request as soon as "someone from the team agrees" (the prerequisite given in `.github/CONTRIBUTING.md`).

**Comment by jennybc** [comment]
@duckmayr usethis is "resting" right now but you should go ahead and make the PR.

**Comment by duckmayr** [comment]
@jennybc Done, thanks! I think the commit message was clear and complete, but feel free to reach out with questions. When you come back to it, something to note is it looks like there was a snag on the AppVeyor build when I opened the PR: The tests I added for the new functions failed as the errors "'RcppArmadillo' must be installed before you can take a dependency on it." and "'RcppEigen' must be installed before you can take a dependency on it."`were thrown from `use_dependency()`, which those functions call. `R CMD check` went through fine on my machine as I have those packages installed, so Since those packages won't be dependencies of `usethis`, I'm not sure what the best practice is to avoid having that test fail on machines that don't have RcppArmadillo and RcppEigen installed -- have it just be a manual test? Have a check *before* the tests and only run them if `requireNamespace("RcppArmadillo", quietly = TRUE)` or `requireNamespace("RcppEigen", quietly = TRUE)` respectively return `TRUE`?

**Comment by jennybc** [comment]
Yeah have a look around the tests for other ways to handle, such as:

  * `skip_if_not_installed()`
  * use a local mock for `use_dependency()` to always return `TRUE`
