### ISSUE TITLE
feature request: use_ccby_license()

### ISSUE THREAD

**Issue by njtierney** [r-lib/usethis#547]
Hello!

I was wondering if there might be interest in a `use_ccby_license()` function?

Happy to submit a PR, if that is of interest.

Cheers,

Nick

**Comment by hadley** [comment]
I don't think that's terribly appropriate since it's not a code license?

**Comment by njtierney** [comment]
Sure, it isn't a code license, but it is very frequently used for data sources, which is the use case I had. Let me know if you think that is in scope for `usethis`, otherwise this sort of function could live in a package for data sharing, if that might be more appropriate.

**Comment by hadley** [comment]
Is it? I'm not sure it's appropriate for data use either? Can you point me to some discussion?

**Comment by njtierney** [comment]
I believe it is. It's used quite extensively in Australia for it's datasources:

- [median house prices](https://data.melbourne.vic.gov.au/Property-Planning/Median-House-Prices-by-Transfer-Year-from-2000-201/67fb-mvax)
- [parking sensor data](https://data.melbourne.vic.gov.au/Transport-Movement/On-street-Car-Parking-Sensor-Data-2013/7jq6-k9kf)
- [public bbqs](https://data.melbourne.vic.gov.au/Assets-Infrastructure/Public-barbecues/5nb5-w7hq)
- [library checkouts](https://www.data.brisbane.qld.gov.au/data/dataset/library-checkouts-branch-date#)
- [traffic management](https://www.data.brisbane.qld.gov.au/data/dataset/traffic-data-at-intersection-api)

It's also discussed here: https://project-open-data.cio.gov/open-licenses/

**Comment by hadley** [comment]
Counter case is argued at https://uc3.cdlib.org/2016/09/19/cc-by-and-data-not-always-a-good-fit/

OTOH https://wiki.creativecommons.org/wiki/Data#Frequently_asked_questions_about_data_and_CC_licenses

So I think we're both partly right: it's not perfect for data (because depending on the jurisdiction, the CC license might not actually apply to anything), but it's not unreasonable, and lots of people are using it already. That makes it a reasonable request, and I'd be happy to review a PR>

**Comment by njtierney** [comment]
OK great, thanks for finding that counter case! That is very useful.

I'll get a PR together and tag you in it. 

Thanks!
