### ISSUE TITLE
Helpers for release-candidate branch

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#558]
* Create branch
* Bump version
* Merge back in after accepted

+ whatever else @jimhester does

**Comment by jimhester** [comment]
That is basically it, but I tag the tip of the branch when it is accepted before merging it back.

I also tend to do the NEWS grooming / cran-comments and other misc. things in the release candidate branch.

One nice thing about doing this is if you end up with multiple back and forths with CRAN about something you can fixup the history in the branch before merging it back.

**Comment by jennybc** [comment]
Where do you commit revdep stuff? As in, which branch. Also release candidate?

**Comment by hadley** [comment]
Yeah, I think that would go in that branch too.

**Comment by hadley** [comment]
cc @thomasp85

**Comment by DavisVaughan** [comment]
Something for closing the release issue when merging after acceptance feels like it would go here!

**Comment by jennybc** [comment]
We have not moved towards this sort of release candidate workflow and I don't *think* it's just because usethis hasn't provided tooling for it. It feels like we've settled into a different pattern. I'm closing this.

If any of you feel this is premature and we do want to pursue it, then feel free to re-open this.

**Comment by hadley** [comment]
We do this fairly routinely for ggplot2, but I don’t think one package justifies turning it into a function in use this.
