### ISSUE TITLE
Should browse_github() consult DESCRIPTION or git remotes? Or both?

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#626]
`browse_github()` is pretty narrow-minded right now. Why would we only look for GitHub links in DESCRIPTION? What about looking at the current git remotes?

**Comment by maxheld83** [comment]
@VerenaHeld and I just ran into this when we were working on a fork of usethis: `browse_github()` kicked us back to the upstream (as per `DESCRIPTION`), though we kinda expected to get to our fork.
So I guess our expectation was to use the git remote, FWIW.

**Comment by hadley** [comment]
`browse_github()` uses `github_link()` which is different to basically every other `github_()` function because it can be applied to any package (i.e. you can call `browse_github("dplyr"))`. This poses some challenges because we can no longer use all the other github helpers based on the remote.  

I think we probably need something like `github_origin()` but for specifically designed to work by parsing package urls; we'd then use that in all `browse_()` functions when `package` is non-NULL. The code is all there, it just needs a some refactoring.

**Comment by jennybc** [comment]
This probably makes sense to sort out when doing the transition to gert then.

**Comment by hadley** [comment]
Also related to #838 and coming up with standard names for the different repos involved in a fork.

**Comment by hadley** [comment]
`github_home()` now consults the git remotes, BugReports, and URLs.

@maxheld83 this doesn't fix your issue because it prefers upstream to origin, but I think that's most compatible with our current conventions.
