### ISSUE TITLE
use_git_config() behavior inconsistent with article

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/usethis#668]
**Edit**: I did not look at this carefully enough; as @cderv points out, this is very likely a documentation issue.

---

As best as I can tell, this was working in usethis 1.4.0:

https://github.com/r-lib/usethis/blob/f08ecb6480310edd0e1c9b24e1d55359056804ec/vignettes/articles/usethis-setup.Rmd#L72-L73

I updated one of my machines to the dev version, and it returns without printing anything to the screen.

The operative code in usethis seems to be in an internal function `git_config()`, which then calls `git2r::config()`:

https://github.com/r-lib/usethis/blob/37a774ea989714619f5c6dcfaff0ece248027b56/R/git-utils.R#L297-L310 

When I updated my usethis, it updated git2r 0.24.0 -> 0.25.2

Happy to dig further, but wanted to surface this now in case you had some ideas already.

Thanks!

**Comment by ijlyttle** [comment]
Upon further consideration, I suspect a "culprit" is the `invisible(old)` line that returns from `usethis:::git_config()`, *not* git2r.

**Comment by cderv** [comment]
@ijlyttle I think this is an intended change as it is documented in the [NEWS file](https://github.com/r-lib/usethis/blob/bfc636c7f9bb005edd8df6c7c16daeb20139646a/NEWS.md#minor-bug-fixes-and-improvements) for the current dev version.

> use_git_config() now invisibly returns the previous values of the settings.

and it is in place since since bbc6b478d942a22dbb924c3200af039af754ceec

also documented 
https://github.com/r-lib/usethis/blob/f08ecb6480310edd0e1c9b24e1d55359056804ec/R/git.R#L105

Before that, yes this function was returning visibly all the time for user name and email only
https://github.com/r-lib/usethis/blob/a4c0113aa7b39b1045f11022a77d6f43206f3f37/R/git.R#L132-L133

now it return invisibly only the modified value. 

I guess only `usethis-setup.Rmd` should be updated ? 
Unless old behaviour should be restored by printing configuration if `interactive()` and no value to modify is provided : `usethis::use_git_config()` ? or like a possible `git_config_sitrep()` ? 
However, `git2r::config()` does exactly this and return a pretty descent list with all the configuration if nothing is modified.

**Comment by ijlyttle** [comment]
Hi @cderv,

Of course, you are correct; my understanding was incomplete :)

Given that this is the intended behavior of `use_git_config()`, I concur with @cderv's suggestion that `usethis-setup.Rmd` be updated, and I would be happy to make such a PR.

![image](https://media.giphy.com/media/4pMX5rJ4PYAEM/giphy.gif)

**Comment by jennybc** [comment]
Yes I'd appreciate a change to the setup vignette. Note that I just pushed a bit of a update to that document myself. But I didn't touch this stuff.
