### ISSUE TITLE
Lots of people don't know what "sitrep" means

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#705]
Sitrep  = "situation report"

Apparently this is not well known.

What should we call such functions? Go back to the `_dr` suffix, meaning "doctor"?

Current examples in usethis: `proj_sitrep()`, `git_sitrep()`. There's also a proposal for `pkg_sitrep()` or `dev_sitrep()` (https://github.com/r-lib/devtools/issues/1970).

**Comment by maelle** [comment]
FWIW I didn't know what "sitrep" meant but I don't find `_dr` clearer because 1) I wouldn't guess at first sight it's "dr" for "doctor" 2) I'd expect it to cure rather than just describe/diagnose the situation (or even to be an useless doctor in statistics :grin:). Maybe using the word "diagnosis" in the name would help?

**Comment by batpigandme** [comment]
I don't think it exactly "diagnoses" either… If we're gonna go doctor-y about it, I think it's more akin to a checkup. Personally, I like sitrep, but as for the best alias ¯\(°_o)/¯

I think the doctor analogue for me would be homebrew `brew doctor`.

**Comment by cderv** [comment]
Just stepping in to share my opinion

`sitrep` is not clear at first when you don't know what this means, but i find that `dr` is less clearer. However, I find that *situation report* is pretty clear. it is kind of like "FWIW", "TIL", "IMHO" and friends. They are used but when you don't know you feel a bit lost. ☺️ 

A good communication with some documentations and blog posts about "Do you know sitrep functions ?" and I think this could be enough to make the community used to it. If use a lot throughout several packages, it would become common. 

Otherwise, `checkup` could be a good candidate because it is not an abbreviation.

**Comment by ijlyttle** [comment]
I like the precision of the term `git_sitrep`, but I find it to be difficult to say - it's a bit of a tongue-twister for me. 

Perhaps you have already discussed, but would `git_report` work?

**Comment by kwstat** [comment]
What about `git_status` ?

**Comment by jennybc** [comment]
> What about `git_status`?

I'm afraid that would be confused with the established git command, i.e. `git status`.

**Comment by gadenbuie** [comment]
Just brainstorming: `git_info()`. It's not an existing git command and is reminiscent of `sessionInfo()`, `Sys.info()`, etc.

**Comment by hadley** [comment]
I think we should stick with sitrep and find a good gif to help people remember it.

**Comment by jennybc** [comment]
s/fetch/sitrep 🤣

![fetch](https://user-images.githubusercontent.com/599454/56322247-60f31500-611d-11e9-92fb-099b09bf68da.gif)

I still like it and am happy to just do a better job educating folks about what a "sitrep" is.

**Comment by batpigandme** [comment]
Currently doing some recon on sitrep gifs…I don't think the term is FUBAR.

**Comment by jimhester** [comment]
I do not like sitrep and it seems many people have issues with it, even native english speakers. I would prefer any of the other suggestions above or possibly `git_report()` or even `git_status_report()` if we want to be verbose...

**Comment by batpigandme** [comment]
Don't you mean `git_situation_report()`, Jim? 😜

**Comment by jimhester** [comment]
I would be fine with `git_situation_report()` honestly...

**Comment by CorradoLanera** [comment]
Reading other issues here, I encountered `git_siterep()`. Honestly, I supposed it was something for WEB sites or something related to tricky reproducible examples. Anyway, when this page appeared at the second entry in a google search, I decide to read it. Now, I have to agree with @cderv that is clear. And it was sufficient to push me to try it. This way I have just discovered I was not "vaccinated" :-) :-) :-) I want to be vaccinated!!! And I search and found `git_vaccinate()`. Great! But, I am also `FALSE` in "git2r supports SSH"... I am studying to solve this too! ;-)

**Comment by hadley** [comment]
I think sitrep is fine; we made reprex work, and at least some people will be able to guess what sitrep means!

**Comment by jimhester** [comment]
I have issues with reprex as well, but 🤷‍♂️

**Comment by hadley** [comment]
@jimhester your point would’ve been stronger if accompanied by a “stop trying to make fetch happen” gif :wink:

**Comment by hadley** [comment]
😳😳😳
