### ISSUE TITLE
use_build_ignore generates invalid regular expression

### ISSUE THREAD

**Issue by edwinvehmaanpera** [r-lib/usethis#722]
When using a wildcard in the files argument the use_build_ignore function generates invalid regex.

For example `use_build_ignore("*.xlsx")` will print `Adding '^*\\.xlsx$' to '.Rbuildignore'` in the console but in fact adds `^*\.xlsx$` (note the difference) which will break devtools::check(). Either way, I believe both are invalid. I believe the correct regex would be `^.*\.xlsx$`. 

What I was trying to do was to ignore all Excel files. There might be some reason not use a wildcard, but in that case the function should just print an error or warning. 

```r
usethis::use_build_ignore("*.xlsx")
```

**Comment by cderv** [comment]
`.Rbuildignore` pattern should be Perl-like regex as said in [Writing R extension](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#index-_002eRbuildignore-file)

> These patterns should be Perl-like regular expressions (see the help for regexp in R for the precise details), one per line, to be matched case-insensitively against the file and directory names relative to the top-level package source directory.

So to escape a specific file, you need to anchor your regex precisely as advice in [R package book](http://r-pkgs.had.co.nz/package.html#package). `usethis::use_build_ignore()` build ignore helps you add those anchor to the provided regex by adding `^` and `$`, but also escaping `.` to `\.` . (note that you need in R to escape with double `\` as in `\\.` to get `\.` when you _cat_ in a file. But it is equivalent.)

However, you can keep a regex without escaping by using `escape = FALSE`
```r
usethis::use_build_ignore("*.xlsx", escape = FALSE)
```
That would add `*.xlsx` as is to `.Rbuildignore`. So if you pass a Perl-like regex directly it will stay as is.
But I guess that would not correspond here to what you expect because `*.xlsx` is not a PERL-like regex but more a glob pattern using wildcard. For that I think the use of `glob2rx` could help 
``` r
glob2rx("*.xlsx")
#> [1] "^.*\\.xlsx$"
``` 
This would work to add the correct regex : `^.*\\.xlsx$` in R that will write to `^.*\.xlsx$` in the file
```r
usethis:::use_build_ignore(glob2rx("*.xlsx"), escape = FALSE)
```

I think this could be a new feature: 
* adding a `glob` argument in usethis that allows 
```r
usethis:::use_build_ignore("*.xlsx", glob = TRUE)
```
and would use `utils::glob2rx()` to convert this kind of glob pattern to correct pattern for `.Rbuildignore`.

* Or maybe replacing `escape = TRUE` running `usethis:::escape_path()` by a call to `glob2rx`. It seems to be equivalent but this needs to be check. 

Hope it helps.

**Comment by jennybc** [comment]
I believe this conversation could lead to improved documentation or examples for `use_build_ignore()`.
