### ISSUE TITLE
update issue template to current github format

### ISSUE THREAD

**Issue by maxheld83** [r-lib/usethis#756]
split off from #755 as suggested by @jennybc.

<img width="1237" alt="old-template" src="https://user-images.githubusercontent.com/5372770/57480004-f27a2080-729e-11e9-8f5d-eac841c03d7e.png">

**Comment by maxheld83** [comment]
maybe *this* might be a tdd candidate?

**Comment by jennybc** [comment]
The intent of this issue was to change the issue template used by `use_tidy_issue_template()`, which #818 PR doesn't do. I.e. we have to change the file `inst/templates/tidy-issue.md`.

I'm going to reopen.

@Maschette Do you want to take another crack at it? I'm going to point out a few things in the original PR.
