### ISSUE TITLE
error when running code as is from use_rmarkdown_template

### ISSUE THREAD

**Issue by ljanda-amplify** [r-lib/usethis#761]
If you run the code as given in the default function signature for `use_markdown_template()`, you encounter an internal function, `asciify()` and therefore an error, which can be confusing to new users

``` r
usethis::use_rmarkdown_template(template_name = "Basic Template",
                        template_dir = tolower(asciify(template_name)),
                        template_description = "the most basic of templates",
                        template_create_dir = FALSE)
#> Error in asciify(template_name): could not find function "asciify"
```
<sup>Created on 2019-05-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jennybc** [comment]
The problem here is that we are revealing a non-exported helper, `asciify()`, which is problematic, when we reveal how the default value of `template_dir` is computed, which is good.

According to the tidyverse principle ["Avoid magical defaults"](https://principles.tidyverse.org/def-magical.html), we've decided this is a practice we'd like to avoid.

Two things need to be done:

  1. The default value of `template_dir` should become `NULL` and, internally, `template_dir` should be set like so:
    ```
    template_dir <- template_dir %||% tolower(asciify(template_name))
    ```
  1. The documentation of `template_dir` needs to be updated to reflect that it will be based on `template_name`, if not supplied.
