### ISSUE TITLE
no date field in DESCRIPTION file

### ISSUE THREAD

**Issue by igordot** [r-lib/usethis#806]
Is it possible to add the date field to the `DESCRIPTION` file with `usethis`? It's trivial to do it manually, but it would be nice to have it done automatically.

I realized it was missing because I got a warning with `citation()`:
```
no date field in DESCRIPTION file of package
```

For those who may not be familiar, from [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html):
> The optional ‘Date’ field gives the release date of the current version of the package.

I saw that there was `use_citation()` but that is more appropriate if you have an article or a book.

**Comment by jennybc** [comment]
We are, in general, anti-`Date` field because it is automatically added when, say, CRAN builds your package and that `Date` will always be correct, by definition. So it turns out that manually tending a `Date` field causes more problems than it solves, because people routinely forget to update it.

Can you describe your situation more, in terms of how this package has been installed?

**Comment by igordot** [comment]
I originally tried this on a development version. The version that was installed from CRAN has the date. Thank you for clarifying. Everything makes sense now.
