### ISSUE TITLE
use_tutorial creates .gitignore in wrong place

### ISSUE THREAD

**Issue by angela-li** [r-lib/usethis#894]
Looks like running use_tutorial creates a .gitignore in the `inst/tutorials` folder instead of the .gitignore in the package base directory, which I assume isn't behavior we want?

I'm partially responsible for this, so will look into fixing it!

**Comment by gadenbuie** [comment]
I think this is okay. `.gitignore` in sub-folders ignores files in that folder (or below), so the `.gitignore` created by `use_tutorial()` only ignores `.html` files created in `inst/tutorials` rather than any `.html` in the package folder. This makes sense because someone *may* want to commit other `.html` files, but it's reasonable to assume that the user doesn't want the to commit the tutorial HTML files.

**Comment by angela-li** [comment]
Oh ok, thanks for the heads up Garrick! Will close this issue then, that makes sense.
