### ISSUE TITLE
Add title to README template

### ISSUE THREAD

**Issue by boshek** [r-lib/usethis#948]
The newest release of pandoc on DEBIAN fails when a README doesn't have a title which then gives a warning in R CMD CHECK. See:

https://stat.ethz.ch/pipermail/r-package-devel/2019q4/004672.html

Would you consider a PR that adds

```yaml
title: README
```

to here:

https://github.com/r-lib/usethis/blob/c7314cf273fba1cb6dad43d8ce84b869e3dfbad7/inst/templates/package-README#L3

and maybe here for consistency:

https://github.com/r-lib/usethis/blob/c7314cf273fba1cb6dad43d8ce84b869e3dfbad7/inst/templates/project-README#L3

**Comment by jennybc** [comment]
I'm not in the right head space to sort this out now myself. But I'll leave a few notes for myself or anyone who pursues this.

 I suspect the real problem is using `output: github_document` and this is just exposing that.

Now that GitHub uses CommonMark, I believe the best way to make markdown aimed at GitHub is, ironically, to use `md_document`, as I do in reprex. We should look into that before making other, pragmatic changes in the template.

**Comment by jennybc** [comment]
Also, I think the real fix for this may belong in rmarkdown and I see commits there that look related. So that's another thing to watch / wait for.

**Comment by hadley** [comment]
I don't see this problem so I think it must've gone away.
