### ISSUE TITLE
`pr_finish()`: Delete local branch if remote was deleted

### ISSUE THREAD

**Issue by pat-s** [r-lib/usethis#950]
When the remote has been deleted and I run `git pull` before `pr_finish()`, I get the following

```r
Error in git2r::fetch(repo, name = remref_remote(remref), credentials = credentials,  : 
  Error in 'git2r_remote_fetch': 'name' must be a character vector of length one with non NA value
```

1. PR gets merged on GH and the branch is deleted
2. Running `git pull` (the deleted remote branch is fetched)
3. When calling `pr_finish()` now, it errors with the msg above because the remote was removed during the `git pull` call

This happens quite often when working on multiple machines. When finishing the PR on one machine, I do not immediately run `pr_finish()` on the other one. Instead I pull first and then run into the problem described above. 
Happy to do a PR if it would be accepted.

## Proposal

`pr_finish()` should check if the remote still exists and (if not) only delete the local branch.

**Comment by jennybc** [comment]
You don't even need to do the `git pull`.

I can replicate with:

  1. Merge PR on gh and delete the branch.
  2. Call `pr_finish()`.

**Comment by jennybc** [comment]
I think (several of?) the checkers should probably present a "Proceed? Y/N" choice when they encounter a non-default situation, instead of erroring unconditionally.

So, in this case, `check_branch_pushed()` is the culprit. If the `remote` branch is `NULL`, we should present a way for the user to say "yeah, keep going with the `pr_finish()`".

**Comment by pat-s** [comment]
Do you want to do this by yourself or should I do a PR?

**Comment by jennybc** [comment]
We have medium-term plans to rework all things git here (switch from git2r to credentials+gert). So I am planning to deal with all the accumulated PR issues at that time.

That being said, I now think I can't get that done and release before rstudio::conf. So a very focused, easy-to-review PR would be appreciated. Because we'll definitely use the `pr_*()` functions at tidyverse dev day.

**Comment by hadley** [comment]
Is this still causing you problems? Because I don't seem to experience this problem anymore — I can merge the PR and delete the branch, and still `pr_fetch()` then `pr_finish()`.

**Comment by pat-s** [comment]
Seems ok now with (latest devel).
