### ISSUE TITLE
Functions that edit README.Rmd break Unicode characters

### ISSUE THREAD

**Issue by rossellhayes** [r-lib/usethis#969]
Functions that edit packages' README.Rmd, like `use_lifecycle_badge()` result in garbled Unicode characters.

For example, after running `use_lifecycle_badge()`, a pronunciation guide "/ˌfoʊ.naɪˈif/" in my package description became "/ËŒfoÊŠ.naÉªËˆif/".

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.
