### ISSUE TITLE
use_tidy_description() (and maybe others) should not write to file if contents are not changed

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/usethis#974]
It can sound like a pedantic detail, but some other processes depend on when DESCRIPTION was modified last, for example some [pre-commit hooks](https://lorenzwalthert.github.io/precommit). I believe in principle, contents often should be written back only when they change, so I thought maybe this principle should be implemented in this package, and potentially also applies to other i/o operations of {usethis}. If you don't think so, I can very easily implement this in https://github.com/lorenzwalthert/precommit for my use case. I can make A PR for this if you are open.

**Comment by jennybc** [comment]
usethis mainly relies on `write_over()` for this and it already does not overwrite if there is no change:

https://github.com/r-lib/usethis/blob/bfc636c7f9bb005edd8df6c7c16daeb20139646a/R/write.R#L74-L76

I suspect your issue is better aimed at ... desc? What exactly is an example that shows the problem you are experiencing?

**Comment by jennybc** [comment]
https://github.com/r-lib/usethis/blob/e364fd057e70df760daa686e92dae7973c8fb274/R/tidyverse.R#L125-L130

I guess you could re-rig this function to somehow route through `write_over()`?

**Comment by lorenzwalthert** [comment]
Ok, then let's leave it for now. If it turns out to be a big deal, I'd consider reopening.
