### ISSUE TITLE
proj_set('.', force=T) doesn't work if proj_set('.') has already been called

### ISSUE THREAD

**Issue by wch** [r-lib/usethis#985]
In the example below, I call `proj_set('.')`, but then realize it's finding the wrong dir, so I call `proj_set('.', force=T)`, but the second call has no effect.

```R
getwd()
#> [1] "/Users/winston"
dir.create('foo')
setwd('foo')
library(usethis)
proj_set('.')
#> ✔ Setting active project to '/Users/winston'
proj_set('.', force=T)
proj_get()
#> /Users/winston
```

However, starting a new R session and calling `usethis::proj_set('.', force=T)` does work.

```R
## Restart R ##
setwd('foo')
usethis::proj_set('.', force=T)
#> ✔ Setting active project to '/Users/winston/foo'
```

Possibly relevant: my home directory has a `.git` directory in it.

**Comment by jennybc** [comment]
I'm not convinced that making this usage work constitutes a net gain. There are at least two fairly non-standard usages:

1. Having a nested project. In @wch's case, _all_ projects will be nested, since his home directory is a git repo, which is one of the primary project-defining criteria for rprojroot, here, and usethis. This is going to be a constant source of pain with all of these packages.
2. Setting the active project to the home directory first, by mistake, then trying to recover.
  - As noted, the `force = TRUE` method does actually work in a fresh session. I believe it would also work in an "unfresh" session, even after setting the project to @wch's home directory, if preceded by `proj_set(NULL, force = TRUE)`.

I propose this is a "wontfix" versus a bug.

**Comment by jennybc** [comment]
I still think this scenario is too far outside our intended, everyday usage to merit changing `proj_set()`.
